// ============================================================
// MODUL LENGKAP BIMBEL BAHASA INGGRIS SD KELAS 1-3 (48 PERTEMUAN)
// ============================================================
const MODULES_DATA = [
  {
    jilid:1, title:'Dasar & Perkenalan', class:'c1',
    range:'Pertemuan 1–12', desc:'Membangun fondasi bahasa Inggris dasar melalui salam, abjad, angka, dan pengenalan diri.',
    topics:['Greetings','Introduction','Alphabet','Numbers','Colors','Shapes','Classroom Objects','Commands','Days','Family','Body Parts','Five Senses'],
    core:['Greetings','Alphabet','Numbers','Colors'],
    pertemuan:[
      {
        num:1, title:'Greetings',
        tujuan:'Siswa mampu menyapa dan merespon salam dalam bahasa Inggris.',
        kosakata:'Hello (halo), Hi (hai), Good Morning (selamat pagi), Good Afternoon (selamat siang), Good Evening (selamat sore/malam), Goodbye (selamat tinggal), See you (sampai jumpa)',
        ekspresi:'Good morning! / Hello! / How are you? / I\'m fine, thank you.',
        grammar:'Penggunaan kata sapaan sederhana tanpa perubahan bentuk kata kerja. Cukup dengan "Good morning!" atau "Hello!"',
        aktivitas:'Setiap siswa maju ke depan kelas dan menyapa 3 teman dengan "Good morning!" lalu berjabat tangan.',
        latihan:'1) Mencocokkan gambar waktu (pagi/siang/sore) dengan sapaan yang tepat. 2) Melengkapi dialog rumpang. 3) Praktek berpasangan.',
        pr:'Tuliskan 5 sapaan dalam bahasa Inggris beserta artinya di buku tugas.',
        materi:'Salam atau <em>greetings</em> adalah cara kita menyapa seseorang. Dalam bahasa Inggris, sapaan disesuaikan dengan waktu: <em>Good morning</em> untuk pagi hari (sebelum pukul 12 siang), <em>Good afternoon</em> untuk siang (pukul 12–18), dan <em>Good evening</em> untuk sore/malam (setelah pukul 18). Untuk situasi informal, cukup gunakan <em>Hello</em> atau <em>Hi</em>. Jika ingin menanyakan kabar, ucapkan "How are you?" dan jawab "I\'m fine, thank you."',
        contoh_kalimat:'Good morning, Teacher! — Selamat pagi, Bu Guru!\nHello, my friend! — Halo, temanku!\nHow are you? — Apa kabarmu?\nI am fine, thank you. — Saya baik-baik saja, terima kasih.\nGoodbye! — Selamat tinggal!',
        contoh_percakapan:'A: Good morning, Rina!\nB: Good morning, Sari!\nA: How are you?\nB: I am fine, thank you. And you?\nA: I am fine too. Goodbye!\nB: Goodbye! See you tomorrow!',
        latihan_soal:'1. Ucapkan "Selamat pagi" dalam bahasa Inggris: _____\n2. Apa jawaban dari "How are you?"\n3. Pasangkan: Pagi → _____, Siang → _____, Malam → _____\n4. Lengkapi: "Good _____" (sampai jumpa)\n5. Tulis 2 sapaan informal dalam bahasa Inggris!',
        tips:'Gunakan lagu "Good Morning" dari YouTube anak-anak. Ajak siswa mempraktikkan sambil bernyanyi dan bergerak.'
      },
      {
        num:2, title:'Introduction',
        tujuan:'Siswa mampu memperkenalkan diri sendiri dalam bahasa Inggris.',
        kosakata:'My name is (nama saya), I am (saya adalah), Your (kamu/mu), What (apa), Nice to meet you (senang bertemu denganmu)',
        ekspresi:'What is your name? — My name is Budi. / I am Budi. / Nice to meet you.',
        grammar:'Pola "My name is…" diikuti nama. "I am…" juga diikuti nama. Tidak ada perubahan kata kerja untuk subjek I (saya).',
        aktivitas:'Setiap siswa berdiri dan memperkenalkan diri ke depan kelas: "Good morning. My name is Budi. Nice to meet you."',
        latihan:'1) Mengisi formulir sederhana dengan nama. 2) Menyusun kata menjadi kalimat perkenalan. 3) Role play perkenalan.',
        pr:'Perkenalkan dirimu dalam bahasa Inggris kepada anggota keluargamu di rumah. Minta mereka menandatangani buku tugas.',
        materi:'Memperkenalkan diri (<em>introduction</em>) adalah kemampuan dasar dalam bahasa Inggris. Gunakan pola "My name is…" (Nama saya…) atau "I am…" (Saya…). Untuk menanyakan nama orang lain, ucapkan "What is your name?" (Siapa namamu?). Setelah berkenalan, ucapkan "Nice to meet you" (Senang bertemu denganmu) sebagai bentuk kesopanan.',
        contoh_kalimat:'My name is Andi. — Nama saya Andi.\nI am Siti. — Saya Siti.\nWhat is your name? — Siapa namamu?\nNice to meet you. — Senang bertemu denganmu.\nNice to meet you too. — Senang juga bertemu denganmu.',
        contoh_percakapan:'A: Hello! What is your name?\nB: My name is Dani. What is your name?\nA: I am Maya. Nice to meet you, Dani.\nB: Nice to meet you too, Maya.',
        latihan_soal:'1. Lengkapi: "_____ is your name?"\n2. Jawab: "My _____ is Rudi."\n3. Apa arti "Nice to meet you"?\n4. Tulis perkenalan singkat (2 kalimat)!\n5. Pasangkan: What → ?, My name → Nama saya',
        tips:'Gunakan boneka tangan untuk berdialog. Siswa lebih berani bicara melalui boneka.'
      },
      {
        num:3, title:'Alphabet',
        tujuan:'Siswa mampu menyebutkan dan mengeja huruf A–Z dalam bahasa Inggris.',
        kosakata:'A-Z, Spell (mengeja), Letter (huruf), Say (ucapkan), Write (tulis)',
        ekspresi:'Spell your name, please. / A for Apple. / B for Ball.',
        grammar:'Tidak ada aturan tata bahasa khusus. Fokus pada pengucapan huruf yang benar (/ei/, /bi:/, /si:/, dll).',
        aktivitas:'Permainan spelling bee: guru menyebutkan kata, siswa mengeja huruf per huruf. Contoh: "Cat" → C-A-T.',
        latihan:'1) Menulis huruf yang hilang. 2) Mengeja nama sendiri. 3) Mencocokkan huruf besar dan kecil.',
        pr:'Tuliskan alfabet A–Z sebanyak 2 kali di buku: sekali huruf besar (capital), sekali huruf kecil (small).',
        materi:'Alfabet bahasa Inggris memiliki 26 huruf: A B C D E F G H I J K L M N O P Q R S T U V W X Y Z. Pengucapan huruf dalam bahasa Inggris berbeda dengan bahasa Indonesia. Contoh: A diucapkan /ei/ (bukan /a/), C diucapkan /si:/ (bukan /ce/), E diucapkan /i:/ (bukan /e/). Hafalkan lagu ABC untuk memudahkan.',
        contoh_kalimat:'Spell your name. — Eja namamu.\nA for Apple. — A untuk Apel.\nB for Ball. — B untuk Bola.\nMy name is B-U-D-I. — Nama saya B-U-D-I.',
        contoh_percakapan:'A: What is your name?\nB: My name is Dina.\nA: Spell your name, please.\nB: D-I-N-A.',
        latihan_soal:'1. Lanjutkan: A B C D E F ___ ___ ___ ___ \n2. Eja namamu sendiri!\n3. Guru bilang "Apple", huruf pertama adalah ___\n4. Berapa jumlah huruf dalam alfabet Inggris?\n5. Sebutkan 3 huruf yang bunyinya berbeda dari bahasa Indonesia!',
        tips:'Putar lagu ABC dari YouTube. Buat flashcards huruf besar dan kecil. Tempel poster alfabet di dinding kelas.'
      },
      {
        num:4, title:'Numbers',
        tujuan:'Siswa mampu menyebutkan angka 1–20 dan menanyakan jumlah.',
        kosakata:'One (satu) — Twenty (dua puluh), plus angka 1–20, How many (berapa banyak), Count (hitung)',
        ekspresi:'How many books? — One book. / I have five pens.',
        grammar:'Penggunaan kata benda jamak (<em>plural</em>) dengan tambahan -s. Contoh: one book, two books. Tidak ada perubahan untuk one (tetap one).',
        aktivitas:'Guru menunjukkan benda (pensil, buku, penghapus), siswa menghitung dalam bahasa Inggris: "One, two, three…"',
        latihan:'1) Menulis angka 1–20 dalam huruf Inggris. 2) Menghitung gambar. 3) Menjawab "How many?"',
        pr:'Hitung jumlah benda di rumahmu (kursi, meja, jendela, pintu) dan tulis dalam bahasa Inggris.',
        materi:'Angka 1–20 dalam bahasa Inggris: one (1), two (2), three (3), four (4), five (5), six (6), seven (7), eight (8), nine (9), ten (10), eleven (11), twelve (12), thirteen (13), fourteen (14), fifteen (15), sixteen (16), seventeen (17), eighteen (18), nineteen (19), twenty (20). Untuk menanyakan jumlah, gunakan "How many…?" (Berapa banyak…?). Perhatikan bahwa kata benda menjadi jamak dengan tambahan -s: one book, two books.',
        contoh_kalimat:'I have five pens. — Saya punya lima pulpen.\nHow many cats? — Berapa banyak kucing?\nI see ten birds. — Saya melihat sepuluh burung.\nThere are three chairs. — Ada tiga kursi.',
        contoh_percakapan:'A: How many pencils do you have?\nB: I have four pencils.\nA: How many books?\nB: Two books.',
        latihan_soal:'1. Tulis: 1=____, 5=____, 10=____, 15=____, 20=____\n2. How many chairs? (gambar 3 kursi) → ____ chairs\n3. 7 + 8 = ____ (tulis dalam huruf Inggris)\n4. Sebutkan angka 1–20 secara berurutan!\n5. "Twelve" artinya ____',
        tips:'Gunakan jari tangan untuk berhitung. Nyanyikan lagu "Five Little Ducks" atau "Ten in the Bed".'
      },
      {
        num:5, title:'Colors',
        tujuan:'Siswa mampu menyebutkan warna-warna dasar dalam bahasa Inggris.',
        kosakata:'Red (merah), Blue (biru), Green (hijau), Yellow (kuning), Black (hitam), White (putih), Pink (merah muda), Orange (oranye), Purple (ungu), Brown (coklat)',
        ekspresi:'What color is it? — It is red. / My favorite color is blue.',
        grammar:'Pola "It is + color" atau "The + noun + is + color". Contoh: The book is blue.',
        aktivitas:'"Color Hunt": Guru menyebutkan warna, siswa mencari benda di sekitar kelas yang berwarna tersebut.',
        latihan:'1) Mewarnai gambar sesuai instruksi. 2) Menebak warna. 3) Menulis nama warna.',
        pr:'Ambil 5 benda di rumah, tulis nama bendanya dan warnanya dalam bahasa Inggris. Contoh: "Book — red."',
        materi:'Warna dasar dalam bahasa Inggris: red (merah), blue (biru), green (hijau), yellow (kuning), black (hitam), white (putih). Warna lainnya: pink (merah muda), orange (oranye), purple (ungu), brown (coklat), gray (abu-abu). Untuk menanyakan warna, gunakan "What color is it?" (Apa warna ini?). Jawab dengan "It is…" (Ini…).',
        contoh_kalimat:'The sky is blue. — Langit berwarna biru.\nThe grass is green. — Rumput berwarna hijau.\nMy bag is red. — Tasku berwarna merah.\nWhat color is your pencil? — Apa warna pensilmu?',
        contoh_percakapan:'A: What color is this? (menunjuk buku)\nB: It is blue.\nA: What color is your bag?\nB: My bag is red.',
        latihan_soal:'1. Warna bendera Indonesia: ____ and ____\n2. Rumput berwarna ____ (inggris)\n3. What color is the sky? → ____\n4. Pasangkan: Merah=____, Kuning=____, Hijau=____\n5. Sebutkan 3 warna kesukaanmu dalam bahasa Inggris!',
        tips:'Gunakan krayon atau kartu warna. Bermain "I Spy" dengan warna: "I spy something blue…"'
      },
      {
        num:6, title:'Shapes',
        tujuan:'Siswa mampu menyebutkan bentuk-bentuk dasar dalam bahasa Inggris.',
        kosakata:'Circle (lingkaran), Square (persegi), Triangle (segitiga), Rectangle (persegi panjang), Star (bintang), Heart (hati), Diamond (belah ketupat), Oval (oval)',
        ekspresi:'It is a circle. / The clock is round. / I draw a square.',
        grammar:'Pola "It is a + shape". Gunakan "a" karena bentuk adalah kata benda tunggal yang diawali konsonan.',
        aktivitas:'Guru menunjukkan gambar bentuk, siswa menebak nama bentuknya dalam bahasa Inggris. Kemudian siswa menggambar bentuk tersebut.',
        latihan:'1) Mencocokkan bentuk dengan namanya. 2) Menebak bentuk benda di kelas. 3) Menggambar bentuk sesuai perintah.',
        pr:'Gambar 5 bentuk berbeda di buku tugas dan beri label namanya dalam bahasa Inggris.',
        materi:'Bentuk-bentuk dasar dalam bahasa Inggris: circle (lingkaran), square (persegi), triangle (segitiga), rectangle (persegi panjang), star (bintang), heart (hati), oval (oval), diamond (belah ketupat). Banyak benda di sekitar kita memiliki bentuk-bentuk ini. Contoh: piring berbentuk circle, buku berbentuk rectangle, dan penggaris segitiga berbentuk triangle.',
        contoh_kalimat:'The plate is a circle. — Piring berbentuk lingkaran.\nThe book is a rectangle. — Buku berbentuk persegi panjang.\nDraw a star! — Gambar bintang!\nThis is a triangle. — Ini segitiga.',
        contoh_percakapan:'A: What shape is this?\nB: It is a circle.\nA: Good! What shape is the door?\nB: The door is a rectangle.',
        latihan_soal:'1. Bola berbentuk ____.\n2. Gambar segitiga dalam bahasa Inggris disebut ____.\n3. Sebutkan 3 benda berbentuk rectangle di kelas!\n4. Pasangkan: Lingkaran=____, Persegi=____, Segitiga=____\n5. Ada berapa sisi (sides) pada sebuah triangle?',
        tips:'Gunakan kertas lipat (origami) untuk membuat bentuk. Ajak siswa mencari bentuk di sekitar kelas.'
      },
      {
        num:7, title:'Classroom Objects',
        tujuan:'Siswa mampu menyebutkan nama benda-benda di kelas dalam bahasa Inggris.',
        kosakata:'Book (buku), Pencil (pensil), Eraser (penghapus), Ruler (penggaris), Bag (tas), Chair (kursi), Table (meja), Door (pintu), Window (jendela), Board (papan tulis)',
        ekspresi:'This is a book. / What is this? — That is a pencil. / I have a ruler.',
        grammar:'Gunakan "This is" untuk benda yang dekat dan "That is" untuk benda yang agak jauh. Gunakan kata sandang "a" untuk benda tunggal.',
        aktivitas:'Guru menyebutkan nama benda, siswa menunjuk benda tersebut. Bergiliran, siswa maju dan menunjuk serta menyebut.',
        latihan:'1) Menempel label bahasa Inggris pada benda di kelas. 2) Menulis nama benda. 3) "What is this?" quiz.',
        pr:'Buat daftar 10 benda di rumahmu beserta nama Inggrisnya. Tempel label pada benda tersebut.',
        materi:'Benda-benda di kelas (<em>classroom objects</em>) adalah kosakata yang dekat dengan keseharian siswa. Beberapa benda utama: book (buku), pencil (pensil), eraser (penghapus), ruler (penggaris), bag (tas), chair (kursi), table (meja), door (pintu), window (jendela), board (papan tulis). Gunakan "This is a…" (Ini…) untuk menunjuk benda yang dipegang atau dekat.',
        contoh_kalimat:'This is a book. — Ini buku.\nThat is a chair. — Itu kursi.\nI have a pencil. — Saya punya pensil.\nOpen the door, please. — Tolong buka pintu.',
        contoh_percakapan:'A: What is this?\nB: This is a pencil.\nA: What is that?\nB: That is a bag.',
        latihan_soal:'1. Alat untuk menulis dalam Inggris: ____\n2. Ini buku: This ____ a book.\n3. Sebutkan 5 benda di kelas dalam bahasa Inggris!\n4. "Penghapus" dalam Inggris: ____\n5. Lengkapi: "Open the ____, please" (pintu)',
        tips:'Buat label berisi nama Inggris untuk semua benda di kelas dan tempelkan. Belajar sambil bermain "Find the object".'
      },
      {
        num:8, title:'Classroom Commands',
        tujuan:'Siswa mampu memahami dan merespon perintah sederhana di kelas.',
        kosakata:'Sit down (duduk), Stand up (berdiri), Open (buka), Close (tutup), Read (baca), Write (tulis), Listen (dengar), Look (lihat), Raise your hand (angkat tangan), Be quiet (diam)',
        ekspresi:'Open your book! / Stand up, please! / Listen carefully!',
        grammar:'Kalimat perintah (imperative) diawali dengan kata kerja (verb) tanpa subjek. Tambahkan "please" agar lebih sopan.',
        aktivitas:'Bermain Simon Says: guru memberi perintah dengan diawali "Simon says" atau tanpa. Siswa hanya melakukan jika diawali "Simon says".',
        latihan:'1) Mencocokkan gambar dengan perintah. 2) Melakukan perintah guru. 3) Memberi perintah ke teman.',
        pr:'Praktikkan 5 perintah kelas di rumah kepada adik atau orang tua. Catat reaksi mereka.',
        materi:'Kalimat perintah (<em>commands</em>) dalam bahasa Inggris sangat sederhana: gunakan kata kerja langsung tanpa subjek. Contoh: "Stand up!" (Berdiri!), "Sit down!" (Duduk!), "Open your book!" (Buka bukumu!). Untuk membuatnya lebih sopan, tambahkan "please": "Sit down, please." Beberapa perintah umum di kelas: raise your hand (angkat tangan), be quiet (diam), listen (dengarkan), repeat (ulangi).',
        contoh_kalimat:'Stand up, please! — Silakan berdiri!\nOpen your book to page 5. — Buka bukumu halaman 5.\nListen carefully! — Dengarkan dengan baik!\nRaise your hand! — Angkat tanganmu!',
        contoh_percakapan:'Teacher: Good morning, class!\nStudents: Good morning, Ma\'am!\nTeacher: Stand up, please.\nStudents: (berdiri)\nTeacher: Sit down, please.',
        latihan_soal:'1. Artikan: "Open the door!"\n2. Bahasa Inggris dari "Duduklah": ____\n3. Jika guru bilang "Be quiet", apa yang harus kamu lakukan?\n4. Lengkapi: "____ your book!" (baca)\n5. Buat 2 kalimat perintah dalam bahasa Inggris!',
        tips:'Gunakan gerakan tubuh saat memberi perintah. Siswa SD belajar paling baik melalui gerakan (TPR — Total Physical Response).'
      },
      {
        num:9, title:'Days',
        tujuan:'Siswa mampu menyebutkan nama-nama hari dalam bahasa Inggris.',
        kosakata:'Monday (Senin), Tuesday (Selasa), Wednesday (Rabu), Thursday (Kamis), Friday (Jumat), Saturday (Sabtu), Sunday (Minggu), Today (hari ini), Yesterday (kemarin), Tomorrow (besok)',
        ekspresi:'What day is today? — Today is Monday. / Tomorrow is Tuesday.',
        grammar:'Nama hari selalu diawali huruf KAPITAL dalam bahasa Inggris. Gunakan kata depan "on" untuk hari: on Monday.',
        aktivitas:'Buat kalender mingguan bersama. Setiap hari tunjuk hari yang benar dan ucapkan bersama-sama.',
        latihan:'1) Mengurutkan hari. 2) Menulis hari hari ini, kemarin, dan besok. 3) Menjawab "What day is today?"',
        pr:'Hafalkan 7 hari dalam bahasa Inggris. Minta orang tua mengetes dan menandatangani buku tugas.',
        materi:'Nama hari dalam bahasa Inggris: Monday (Senin), Tuesday (Selasa), Wednesday (Rabu), Thursday (Kamis), Friday (Jumat), Saturday (Sabtu), Sunday (Minggu). Perhatikan bahwa semua nama hari diawali dengan huruf kapital. Untuk menanyakan hari, gunakan "What day is today?" (Hari ini hari apa?). Gunakan "on" sebelum hari: I go to school on Monday (Saya pergi ke sekolah pada hari Senin).',
        contoh_kalimat:'Today is Monday. — Hari ini Senin.\nTomorrow is Tuesday. — Besok Selasa.\nYesterday was Sunday. — Kemarin Minggu.\nI go to school on Monday. — Saya ke sekolah pada hari Senin.',
        contoh_percakapan:'A: What day is today?\nB: Today is Wednesday.\nA: What day is tomorrow?\nB: Tomorrow is Thursday.',
        latihan_soal:'1. Urutkan: Monday, ____, ____, ____, Friday, ____, Sunday\n2. Hari ini Rabu: Today is ____.\n3. Besok Kamis: ____ is Thursday.\n4. Hari apa setelah Friday? ____\n5. Sebutkan 3 hari favoritmu dalam bahasa Inggris!',
        tips:'Nyanyikan lagu "Days of the Week" (nada: The Addams Family). Tempel poster hari di dinding kelas.'
      },
      {
        num:10, title:'Family',
        tujuan:'Siswa mampu menyebutkan anggota keluarga dalam bahasa Inggris.',
        kosakata:'Father (ayah), Mother (ibu), Brother (saudara laki-laki), Sister (saudara perempuan), Grandfather (kakek), Grandmother (nenek), Uncle (paman), Aunt (bibi), Cousin (sepupu), Baby (bayi)',
        ekspresi:'This is my mother. / I have one brother. / My father is tall.',
        grammar:'Gunakan "my" (milikku) sebelum kata keluarga: my mother, my father. Gunakan "This is" untuk memperkenalkan seseorang.',
        aktivitas:'Setiap siswa membawa foto keluarga atau menggambar pohon keluarga (family tree) dan memperkenalkan anggota keluarganya.',
        latihan:'1) Membuat family tree. 2) Menulis nama anggota keluarga. 3) Memperkenalkan keluarga di depan kelas.',
        pr:'Gambar keluargamu dan beri label nama Inggrisnya (father, mother, dll).',
        materi:'Anggota keluarga (<em>family members</em>) adalah kosakata penting dalam bahasa Inggris. Keluarga inti (<em>nuclear family</em>): father (ayah), mother (ibu), brother (kakak/adik laki-laki), sister (kakak/adik perempuan). Keluarga besar (<em>extended family</em>): grandfather (kakek), grandmother (nenek), uncle (paman), aunt (bibi), cousin (sepupu). Gunakan "This is my…" untuk memperkenalkan: "This is my mother."',
        contoh_kalimat:'This is my mother. — Ini ibuku.\nI have one sister. — Saya punya satu saudari.\nMy father is a teacher. — Ayahku seorang guru.\nI love my family. — Saya sayang keluargaku.',
        contoh_percakapan:'A: Who is this? (menunjuk foto)\nB: This is my mother.\nA: Do you have a brother?\nB: Yes, I have one brother.',
        latihan_soal:'1. Ayah dalam Inggris: ____\n2. Ibu dalam Inggris: ____\n3. "My sister" artinya ____\n4. Sebutkan anggota keluarga inti (4 orang) dalam Inggris!\n5. Lengkapi: "This is ____ grandmother." (nenekku)',
        tips:'Minta siswa membawa foto keluarga. Bermain peran "Family Visit" di kelas.'
      },
      {
        num:11, title:'Body Parts',
        tujuan:'Siswa mampu menyebutkan bagian-bagian tubuh dalam bahasa Inggris.',
        kosakata:'Head (kepala), Hair (rambut), Eyes (mata), Nose (hidung), Mouth (mulut), Ears (telinga), Shoulders (bahu), Hands (tangan), Fingers (jari), Legs (kaki), Feet (telapak kaki), Arms (lengan)',
        ekspresi:'Touch your nose! / I have two eyes. / This is my head.',
        grammar:'Gunakan kata sifat posesif "my" (milikku) dan "your" (milikmu). Perhatikan bentuk jamak: one eye → two eyes, one foot → two feet.',
        aktivitas:'Bernyanyi "Head, Shoulders, Knees and Toes" sambil menunjuk bagian tubuh. Permainan: "Simon says touch your nose."',
        latihan:'1) Menunjuk bagian tubuh sesuai perintah. 2) Memberi label pada gambar tubuh. 3) Menulis nama bagian tubuh.',
        pr:'Gambar tubuh manusia dan beri label minimal 8 bagian tubuh dalam bahasa Inggris.',
        materi:'Bagian tubuh (<em>body parts</em>) adalah kosakata yang mudah dipelajari sambil bergerak. Bagian tubuh utama: head (kepala), hair (rambut), eyes (mata), nose (hidung), mouth (mulut), ears (telinga), shoulders (bahu), arms (lengan), hands (tangan), fingers (jari), legs (kaki), feet (telapak kaki). Perhatikan beberapa bentuk jamak tidak beraturan: foot → feet, tooth → teeth.',
        contoh_kalimat:'Touch your nose! — Sentuh hidungmu!\nI have two eyes. — Saya punya dua mata.\nThis is my hand. — Ini tanganku.\nClose your eyes. — Tutup matamu.',
        contoh_percakapan:'Teacher: Touch your head!\nStudents: (menunjuk kepala)\nTeacher: Good! Now touch your shoulders!\nStudents: (menunjuk bahu)',
        latihan_soal:'1. Hidung dalam Inggris: ____\n2. "Eyes" artinya ____\n3. Ada berapa jari (fingers) di satu tangan?\n4. Sebutkan 5 bagian tubuh dalam bahasa Inggris!\n5. Lengkapi: "Open your ____!" (mulut)',
        tips:'Lagu "Head, Shoulders, Knees and Toes" wajib! Sangat efektif untuk menghafal bagian tubuh.'
      },
      {
        num:12, title:'Five Senses & Review',
        tujuan:'Siswa mampu menyebutkan panca indera dan mereview materi Jilid 1.',
        kosakata:'See (melihat), Hear (mendengar), Smell (mencium), Taste (merasakan), Touch (menyentuh), Eyes (mata), Ears (telinga), Nose (hidung), Tongue (lidah), Skin (kulit)',
        ekspresi:'I can see with my eyes. / I can hear with my ears. / I can taste with my tongue.',
        grammar:'Pola "I can + verb" untuk menyatakan kemampuan. "With" untuk menunjukkan alat yang digunakan.',
        aktivitas:'Kuis review mencakup semua materi Jilid 1: greetings, introduction, alphabet, numbers, colors, shapes, objects, commands, days, family, body parts.',
        latihan:'Review soal dari semua pertemuan. Speaking test: siswa maju satu per satu untuk perkenalan singkat.',
        pr:'Belajar kembali semua materi Jilid 1 untuk persiapan kuis pertemuan berikutnya.',
        materi:'Panca indera (<em>five senses</em>) membantu kita memahami dunia: eyes untuk see (melihat), ears untuk hear (mendengar), nose untuk smell (mencium), tongue untuk taste (merasakan), skin untuk touch (menyentuh). Gunakan pola "I can… with my…": I can see with my eyes. Pertemuan ini juga mereview seluruh materi Jilid 1 sebagai persiapan sebelum naik ke Jilid 2.',
        contoh_kalimat:'I can see the rainbow. — Saya bisa melihat pelangi.\nI can hear the music. — Saya bisa mendengar musik.\nI can smell the flower. — Saya bisa mencium bunga.\nI can taste the ice cream. — Saya bisa merasakan es krim.',
        contoh_percakapan:'A: What can you see?\nB: I can see a book.\nA: What can you hear?\nB: I can hear a bird.',
        latihan_soal:'1. Kita melihat dengan ____.\n2. "I can hear with my ____."\n3. Sebutkan 5 panca indera dalam bahasa Inggris!\n4. Review: Hari ini Selasa = Today is ____\n5. Review: Ucapkan "Selamat pagi" dalam Inggris!',
        tips:'Bawa benda-benda untuk dirasakan, dicium, dilihat. Kuis interaktif dengan hadiah kecil untuk motivasi.'
      }
    ]
  },
  {
    jilid:2, title:'Hewan, Makanan & Alam', class:'c2',
    range:'Pertemuan 13–24', desc:'Memperluas kosakata tematik seputar hewan, makanan, cuaca, dan pakaian dengan pola kalimat sederhana.',
    topics:['Animals','Wild & Farm','Food','Drinks','Fruits','Vegetables','Likes/Dislikes','Clothes','Weather','Seasons','Review','Mid Test'],
    core:['Animals','Food','Fruits','Weather'],
    pertemuan:[
      {
        num:13, title:'Animals',
        tujuan:'Siswa mampu menyebutkan nama-nama hewan peliharaan dan hewan sekitar.',
        kosakata:'Cat (kucing), Dog (anjing), Bird (burung), Fish (ikan), Rabbit (kelinci), Hamster (hamster), Turtle (kura-kura), Duck (bebek), Chicken (ayam), Cow (sapi)',
        ekspresi:'It is a cat. / I have a dog. / The bird can fly.',
        grammar:'Pola "It is a + animal" untuk menunjukkan hewan. Gunakan "a" untuk hewan tunggal. "Can" untuk kemampuan hewan.',
        aktivitas:'Tebak hewan: guru menjelaskan ciri-ciri, siswa menebak nama hewan dalam bahasa Inggris. Contoh: "It is small. It says meow. What is it?"',
        latihan:'Membaca deskripsi hewan, mencocokkan gambar dengan nama, menulis nama hewan, dan berbicara tentang hewan peliharaan.',
        pr:'Hafalkan 10 nama hewan dalam bahasa Inggris. Buatlah flashcards bergambar hewan.',
        materi:'Hewan (<em>animals</em>) dibagi menjadi beberapa jenis: hewan peliharaan (<em>pets</em>) seperti cat (kucing), dog (anjing), fish (ikan), bird (burung), rabbit (kelinci). Hewan ternak (<em>farm animals</em>) seperti cow (sapi), chicken (ayam), duck (bebek), goat (kambing), horse (kuda). Untuk mendeskripsikan hewan, gunakan "It is…" untuk ciri-ciri dan "It can…" untuk kemampuan.',
        contoh_kalimat:'It is a cat. — Ini kucing.\nThe bird can fly. — Burung bisa terbang.\nI have a rabbit. — Saya punya kelinci.\nThe fish swims. — Ikan berenang.',
        contoh_percakapan:'A: What animal is this? (menunjuk gambar)\nB: It is a dog.\nA: What can a dog do?\nB: A dog can run.',
        latihan_soal:'1. Kucing dalam Inggris: ____\n2. "It is a bird" artinya ____\n3. Hewan apa yang bisa terbang? ____\n4. Sebutkan 4 hewan peliharaan dalam bahasa Inggris!\n5. Lengkapi: "A ____ says meow."',
        tips:'Gunakan boneka hewan atau gambar berwarna. Bermain "Animal Sounds" — tebak hewan dari suaranya.'
      },
      {
        num:14, title:'Wild & Farm Animals',
        tujuan:'Siswa mampu membedakan hewan liar dan hewan ternak dalam bahasa Inggris.',
        kosakata:'Lion (singa), Tiger (harimau), Elephant (gajah), Giraffe (jerapah), Monkey (kera), Snake (ular), Cow (sapi), Goat (kambing), Horse (kuda), Sheep (domba), Pig (babi)',
        ekspresi:'It lives in the jungle. / It lives on a farm. / The lion is wild.',
        grammar:'Pola "It lives in/on…" untuk menunjukkan habitat. Gunakan "The + animal + is + adjective" untuk deskripsi.',
        aktivitas:'Permainan sorting: kelompokkan gambar hewan ke dalam dua kategori "Wild Animals" dan "Farm Animals".',
        latihan:'Membaca teks pendek tentang hewan, mengelompokkan hewan, menulis nama hewan sesuai kategori.',
        pr:'Buat 2 kolom: "Wild Animals" dan "Farm Animals". Tulis minimal 4 hewan di setiap kolom.',
        materi:'Hewan liar (<em>wild animals</em>) hidup di alam bebas seperti hutan atau savana: lion (singa), tiger (harimau), elephant (gajah), giraffe (jerapah), monkey (kera), snake (ular), zebra (zebra), crocodile (buaya). Hewan ternak (<em>farm animals</em>) dipelihara oleh manusia di peternakan: cow (sapi), goat (kambing), horse (kuda), sheep (domba), pig (babi), duck (bebek), chicken (ayam).',
        contoh_kalimat:'A lion lives in the jungle. — Singa tinggal di hutan.\nA cow lives on a farm. — Sapi tinggal di peternakan.\nThe elephant is big. — Gajah itu besar.\nA monkey can climb. — Kera bisa memanjat.',
        contoh_percakapan:'A: Where does a lion live?\nB: A lion lives in the jungle.\nA: Where does a cow live?\nB: A cow lives on a farm.',
        latihan_soal:'1. Singa adalah hewan: ____ (wild/farm)\n2. Sapi adalah hewan: ____ (wild/farm)\n3. Sebutkan 2 hewan liar dalam Inggris!\n4. "It lives on a farm" artinya ____\n5. Hewan terbesar di darat dalam Inggris: ____',
        tips:'Gunakan video pendek tentang hewan dari National Geographic Kids. Buku gambar/binatang plastik untuk sorting.'
      },
      {
        num:15, title:'Food',
        tujuan:'Siswa mampu menyebutkan nama-nama makanan dalam bahasa Inggris.',
        kosakata:'Rice (nasi), Bread (roti), Milk (susu), Egg (telur), Noodle (mie), Cheese (keju), Butter (mentega), Meat (daging), Chicken (ayam), Fish (ikan), Cake (kue), Biscuit (biskuit)',
        ekspresi:'I like bread. / I eat rice every day. / Do you like milk?',
        grammar:'Gunakan "I like…" untuk menyatakan suka dan "I don\'t like…" untuk tidak suka. "Do you like…?" untuk bertanya.',
        aktivitas:'Flashcard makanan: guru menunjukkan gambar, siswa menyebut nama makanannya. Berdialog tentang makanan favorit.',
        latihan:'Membaca menu sederhana, mencocokkan gambar dengan nama makanan, menulis makanan favorit, berdialog tentang makanan.',
        pr:'Tulis 5 makanan favoritmu dalam bahasa Inggris. Gambar atau tempel fotonya.',
        materi:'Makanan (<em>food</em>) adalah kosakata yang dekat dengan kehidupan sehari-hari. Makanan pokok: rice (nasi), bread (roti), noodle (mie). Lauk: chicken (ayam), fish (ikan), meat (daging), egg (telur). Minuman: milk (susu), water (air), juice (jus). Camilan: cake (kue), biscuit (biskuit), chocolate (coklat). Untuk menyatakan suka, gunakan "I like…". Untuk tidak suka, "I don\'t like…"',
        contoh_kalimat:'I like rice. — Saya suka nasi.\nI don\'t like milk. — Saya tidak suka susu.\nDo you like bread? — Apakah kamu suka roti?\nI eat chicken for dinner. — Saya makan ayam untuk makan malam.',
        contoh_percakapan:'A: Do you like rice?\nB: Yes, I like rice.\nA: Do you like milk?\nB: No, I don\'t like milk.',
        latihan_soal:'1. Nasi dalam Inggris: ____\n2. "I like bread" artinya ____\n3. Tanya teman: "Do you like ____?"\n4. Sebutkan 4 makanan dalam bahasa Inggris!\n5. Lengkapi: "I eat ____ for breakfast." (telur)',
        tips:'Bawa makanan asli atau mainan makanan. Bermain "Market Day" di kelas dengan menu bahasa Inggris.'
      },
      {
        num:16, title:'Drinks',
        tujuan:'Siswa mampu menyebutkan nama-nama minuman dalam bahasa Inggris.',
        kosakata:'Water (air putih), Milk (susu), Juice (jus), Tea (teh), Coffee (kopi), Soda (soda), Hot chocolate (coklat panas), Lemonade (limun), Syrup (sirup), Coconut water (air kelapa)',
        ekspresi:'Can I have water? / I want to drink juice. / This is tea.',
        grammar:'Gunakan "Can I have…?" untuk meminta sesuatu dengan sopan. "I want to drink…" untuk menyatakan keinginan.',
        aktivitas:'Role play di restoran: siswa bergantian menjadi pelayan dan pembeli, memesan minuman dalam bahasa Inggris.',
        latihan:'Membaca dialog di restoran, mencocokkan gambar minuman, menulis nama minuman, bermain peran.',
        pr:'Tulis 5 nama minuman dalam bahasa Inggris beserta artinya. Hafalkan cara memesan minuman.',
        materi:'Minuman (<em>drinks</em>) dalam bahasa Inggris: water (air putih), milk (susu), juice (jus), tea (teh), coffee (kopi), hot chocolate (coklat panas), lemonade (limun), syrup (sirup), soda (soda), mineral water (air mineral). Untuk meminta minuman dengan sopan, gunakan "Can I have…, please?" (Boleh saya minta…?). Contoh: "Can I have water, please?"',
        contoh_kalimat:'Can I have water, please? — Boleh saya minta air?\nI want to drink juice. — Saya ingin minum jus.\nThis tea is hot. — Teh ini panas.\nThe milk is cold. — Susunya dingin.',
        contoh_percakapan:'A: Can I have milk, please?\nB: Here you are.\nA: Thank you.\nB: You\'re welcome.',
        latihan_soal:'1. Air putih dalam Inggris: ____\n2. "Can I have juice?" artinya ____\n3. Sebutkan 3 minuman dalam bahasa Inggris!\n4. Lengkapi: "I want to ____ milk." (minum)\n5. Apa jawaban dari "Can I have water?"',
        tips:'Bawa gelas plastik dan air minum. Praktik langsung role play "At the Cafe".'
      },
      {
        num:17, title:'Fruits',
        tujuan:'Siswa mampu menyebutkan nama-nama buah dalam bahasa Inggris.',
        kosakata:'Apple (apel), Banana (pisang), Orange (jeruk), Grape (anggur), Mango (mangga), Watermelon (semangka), Papaya (pepaya), Pineapple (nanas), Strawberry (stroberi), Melon (melon), Durian (durian), Guava (jambu)',
        ekspresi:'I like apples. / This is a banana. / The mango is sweet.',
        grammar:'Perhatikan bentuk jamak: apple → apples, banana → bananas. Gunakan "I like + plural noun" (I like apples).',
        aktivitas:'"Fruit Market": guru menjadi penjual buah, siswa membeli buah menggunakan dialog bahasa Inggris.',
        latihan:'Membaca daftar harga buah, mencocokkan gambar dengan nama, menulis buah favorit, bermain peran jual-beli.',
        pr:'Gambar 5 buah favoritmu dan beri label nama Inggrisnya. Warnai dengan rapi.',
        materi:'Buah-buahan (<em>fruits</em>) adalah makanan sehat yang kaya vitamin. Nama buah dalam bahasa Inggris: apple (apel), banana (pisang), orange (jeruk), grape (anggur), mango (mangga), watermelon (semangka), papaya (pepaya), pineapple (nanas), strawberry (stroberi), melon (melon), durian (durian), guava (jambu). Untuk menyatakan suka buah, gunakan "I like…" dengan bentuk jamak: "I like apples."',
        contoh_kalimat:'I like apples. — Saya suka apel.\nThe banana is yellow. — Pisang itu kuning.\nThis mango is sweet. — Mangga ini manis.\nDo you like oranges? — Apakah kamu suka jeruk?',
        contoh_percakapan:'A: What fruit do you like?\nB: I like bananas.\nA: What color is a banana?\nB: It is yellow.',
        latihan_soal:'1. Apel dalam Inggris: ____\n2. Pisang dalam Inggris: ____\n3. "I like grapes" artinya ____\n4. Sebutkan 4 buah dalam bahasa Inggris!\n5. Buah apa yang berwarna kuning dan panjang? ____',
        tips:'Bawa buah asli ke kelas. Minta siswa merasakan dan menebak nama buahnya.'
      },
      {
        num:18, title:'Vegetables',
        tujuan:'Siswa mampu menyebutkan nama-nama sayuran dalam bahasa Inggris.',
        kosakata:'Carrot (wortel), Tomato (tomat), Onion (bawang merah), Cabbage (kubis), Spinach (bayam), Broccoli (brokoli), Cucumber (mentimun), Corn (jagung), Potato (kentang), Bean (kacang), Mushroom (jamur), Chili (cabai)',
        ekspresi:'I like carrots. / I don\'t like onion. / This is a tomato.',
        grammar:'Gunakan "I don\'t like…" untuk menyatakan tidak suka. Kata benda jamak: carrot → carrots, tomato → tomatoes.',
        aktivitas:'Permainan mencocokkan: guru menyebut nama sayuran dalam Inggris, siswa menunjuk gambar yang tepat.',
        latihan:'Membaca teks tentang sayuran, mengelompokkan sayuran berdasarkan warna, menulis nama sayuran.',
        pr:'Tulis 7 nama sayuran dalam bahasa Inggris. Sebutkan sayuran yang kamu suka dan tidak suka.',
        materi:'Sayuran (<em>vegetables</em>) penting untuk kesehatan. Nama sayuran dalam bahasa Inggris: carrot (wortel), tomato (tomat), onion (bawang merah), garlic (bawang putih), cabbage (kubis), spinach (bayam), broccoli (brokoli), cucumber (mentimun), corn (jagung), potato (kentang), bean (kacang), mushroom (jamur), chili (cabai). "Vegetables" adalah bentuk jamak; kata dasarnya "vegetable".',
        contoh_kalimat:'I like carrots. — Saya suka wortel.\nI don\'t like onions. — Saya tidak suka bawang.\nTomatoes are red. — Tomat berwarna merah.\nCorn is yellow. — Jagung berwarna kuning.',
        contoh_percakapan:'A: Do you like carrots?\nB: Yes, I do. I like carrots.\nA: Do you like onions?\nB: No, I don\'t like onions.',
        latihan_soal:'1. Wortel dalam Inggris: ____\n2. "I don\'t like spinach" artinya ____\n3. Sayuran apa yang berwarna orange? ____\n4. Sebutkan 3 sayuran dalam bahasa Inggris!\n5. Lengkapi: "Tomatoes are ____" (merah).',
        tips:'Gunakan teka-teki silang bergambar. Tempel poster sayuran di dinding kelas.'
      },
      {
        num:19, title:'Likes & Dislikes',
        tujuan:'Siswa mampu menyatakan suka dan tidak suka dalam bahasa Inggris.',
        kosakata:'Like (suka), Don\'t like (tidak suka), Love (sangat suka), Hate (benci), Favorite (favorit), Do you (apakah kamu), Yes I do, No I don\'t',
        ekspresi:'Do you like…? — Yes, I like… / No, I don\'t like… / I love… / I hate…',
        grammar:'Pola tanya: "Do you like + noun?" Jawab: "Yes, I do" atau "No, I don\'t". Gunakan "I like" untuk suka, "I don\'t like" untuk tidak suka.',
        aktivitas:'Wawancara teman sekelas: setiap siswa bertanya ke 3 teman "Do you like…?" dan mencatat jawabannya di tabel.',
        latihan:'Membaca hasil wawancara, menulis 5 kalimat tentang suka/tidak suka, mempresentasikan ke depan kelas.',
        pr:'Tulis 5 kalimat: 2 tentang hal yang kamu suka, 2 tentang yang tidak suka, dan 1 tentang yang kamu love.',
        materi:'Menyatakan suka (<em>likes</em>) dan tidak suka (<em>dislikes</em>) adalah ekspresi penting. Gunakan "I like…" (Saya suka…), "I don\'t like…" (Saya tidak suka…), dan "I love…" (Saya sangat suka…). Untuk bertanya: "Do you like…?" (Apakah kamu suka…?). Jawaban singkat: "Yes, I do" atau "No, I don\'t". Kata "favorite" berarti favorit/kesukaan.',
        contoh_kalimat:'I like ice cream. — Saya suka es krim.\nI don\'t like spiders. — Saya tidak suka laba-laba.\nI love my family. — Saya sangat sayang keluarga.\nMy favorite color is blue. — Warna favoritku biru.',
        contoh_percakapan:'A: Do you like ice cream?\nB: Yes, I do. I like ice cream. Do you like broccoli?\nA: No, I don\'t like broccoli.',
        latihan_soal:'1. Bahasa Inggris dari "Saya suka apel": ____\n2. Artikan: "I don\'t like spiders" ____\n3. Tanya teman: "____ you like cats?"\n4. Jawab singkat suka: "Yes, ____ ____"\n5. Buat 2 kalimat tentang hal yang kamu suka!',
        tips:'Gunakan diagram Venn untuk membandingkan suka/tidak suka antar siswa. Sangat interaktif dan seru.'
      },
      {
        num:20, title:'Clothes',
        tujuan:'Siswa mampu menyebutkan nama-nama pakaian dalam bahasa Inggris.',
        kosakata:'Shirt (kemeja), Pants (celana), Shoes (sepatu), Socks (kaos kaki), Hat (topi), Jacket (jaket), Dress (gaun), Skirt (rok), Shorts (celana pendek), T-shirt (kaos), Belt (ikat pinggang), Uniform (seragam)',
        ekspresi:'I am wearing a shirt. / Put on your shoes! / This is a hat.',
        grammar:'Gunakan "I am wearing…" (Saya memakai…) untuk menjelaskan pakaian yang dikenakan. Kata kerja "wear" berarti memakai.',
        aktivitas:'"Fashion Show": siswa maju ke depan dan menjelaskan pakaian yang mereka kenakan dalam bahasa Inggris. "I am wearing a blue shirt and white shoes."',
        latihan:'Membaca deskripsi pakaian, mencocokkan gambar, menulis nama pakaian, fashion show presentation.',
        pr:'Buka lemari pakaianmu. Tulis 5 nama pakaian dalam bahasa Inggris beserta warnanya.',
        materi:'Pakaian (<em>clothes</em>) dalam bahasa Inggris: shirt (kemeja), T-shirt (kaos), pants (celana), shorts (celana pendek), skirt (rok), dress (gaun), jacket (jaket), sweater (sweater), shoes (sepatu), socks (kaos kaki), hat (topi), belt (ikat pinggang), uniform (seragam). Perhatikan bahwa pants dan shorts menggunakan bentuk jamak. Gunakan "I am wearing…" untuk menyatakan pakaian yang sedang dikenakan.',
        contoh_kalimat:'I am wearing a blue shirt. — Saya memakai kemeja biru.\nPut on your shoes! — Pakai sepatumu!\nThis dress is beautiful. — Gaun ini cantik.\nMy uniform is white and grey. — Seragamku putih dan abu-abu.',
        contoh_percakapan:'A: What are you wearing?\nB: I am wearing a red T-shirt and blue shorts.\nA: What color are your shoes?\nB: My shoes are black.',
        latihan_soal:'1. Kemeja dalam Inggris: ____\n2. "Shoes" artinya ____\n3. I am ____ a jacket. (memakai)\n4. Sebutkan 4 pakaian dalam bahasa Inggris!\n5. Apa yang kamu pakai hari ini? Jawab dalam Inggris!',
        tips:'Bawa majalah bekas, minta siswa gunting gambar pakaian dan beri label. Bermain "What am I wearing?" - tebak-tebakan.'
      },
      {
        num:21, title:'Weather',
        tujuan:'Siswa mampu menyebutkan kondisi cuaca dalam bahasa Inggris.',
        kosakata:'Sunny (cerah), Rainy (hujan), Cloudy (mendung), Windy (berangin), Hot (panas), Cold (dingin), Warm (hangat), Stormy (badai), Foggy (berkabut), Snowy (bersalju)',
        ekspresi:'How\'s the weather? — It is sunny today. / It is raining. / It is hot.',
        grammar:'Pola "It is + adjective" untuk cuaca. "It is raining" menggunakan continuous verb. Tanya "How\'s the weather?" (Bagaimana cuacanya?).',
        aktivitas:'Buat chart cuaca mingguan. Setiap hari, siswa bergiliran melihat ke luar jendela dan melaporkan cuaca dalam bahasa Inggris.',
        latihan:'Membaca laporan cuaca sederhana, mencocokkan gambar cuaca, menulis laporan cuaca harian.',
        pr:'Catat cuaca selama 3 hari ke depan. Tulis dalam bahasa Inggris: "Today is…"',
        materi:'Cuaca (<em>weather</em>) dalam bahasa Inggris: sunny (cerah), rainy (hujan), cloudy (mendung), windy (berangin), hot (panas), cold (dingin), warm (hangat), stormy (berbadai), foggy (berkabut). Untuk menanyakan cuaca: "How\'s the weather?" (Bagaimana cuacanya?). Jawab: "It is sunny" (Cerah), "It is raining" (Sedang hujan), "It is hot" (Panas). Perhatikan penggunaan "It is" untuk cuaca.',
        contoh_kalimat:'It is sunny today. — Hari ini cerah.\nIt is raining outside. — Di luar sedang hujan.\nThe weather is cold. — Cuacanya dingin.\nIt is very hot. — Cuacanya sangat panas.',
        contoh_percakapan:'A: How\'s the weather today?\nB: It is sunny and hot.\nA: Do you like rainy days?\nB: No, I don\'t. I like sunny days.',
        latihan_soal:'1. "Sunny" artinya ____.\n2. Tanya cuaca: "____ the weather?"\n3. Sekarang hujan: "It is ____."\n4. Sebutkan 3 cuaca dalam bahasa Inggris!\n5. Cuaca apa yang kamu suka? Mengapa?',
        tips:'Buat "weather wheel" dari karton. Putar setiap hari. Lagu "How\'s the Weather?" dari Super Simple Songs.'
      },
      {
        num:22, title:'Seasons',
        tujuan:'Siswa mampu menyebutkan musim dan ciri-cirinya dalam bahasa Inggris.',
        kosakata:'Spring (musim semi), Summer (musim panas), Autumn/Fall (musim gugur), Winter (musim dingin), Season (musim), Flower (bunga), Leaves (daun), Snow (salju), Sun (matahari), Rain (hujan)',
        ekspresi:'My favorite season is summer. / Spring is warm. / It snows in winter.',
        grammar:'Gunakan "in" sebelum nama musim: in spring, in summer. Gunakan "My favorite season is…" untuk menyatakan musim favorit.',
        aktivitas:'Guru menunjukkan gambar 4 musim dari negara subtropis. Siswa menebak nama musim dan mendeskripsikannya.',
        latihan:'Membaca teks tentang 4 musim, mencocokkan gambar musim, menulis deskripsi musim favorit.',
        pr:'Gambar dan beri label 4 musim dalam bahasa Inggris. Tulis satu kalimat untuk setiap musim.',
        materi:'Musim (<em>seasons</em>) di negara subtropis: spring (musim semi — bunga bermekaran, hangat), summer (musim panas — sangat panas, liburan), autumn/fall (musim gugur — daun berjatuhan, sejuk), winter (musim dingin — salju turun, sangat dingin). Di Indonesia hanya ada 2 musim: dry season (musim kemarau) dan rainy season (musim hujan). Gunakan kata depan "in" sebelum musim: "in summer."',
        contoh_kalimat:'My favorite season is summer. — Musim favoritku adalah panas.\nIt is hot in summer. — Panas di musim panas.\nLeaves fall in autumn. — Daun berjatuhan di musim gugur.\nIt snows in winter. — Turun salju di musim dingin.',
        contoh_percakapan:'A: What is your favorite season?\nB: My favorite season is spring.\nA: Why do you like spring?\nB: Because the flowers are beautiful.',
        latihan_soal:'1. Ada berapa musim di negara subtropis? ____\n2. "Summer" artinya ____\n3. Musim favoritku adalah: "My ____ season is ____"\n4. Di musim apa salju turun? ____\n5. Sebutkan 2 musim di Indonesia!',
        tips:'Tonton video "Four Seasons" dari National Geographic. Gunakan lagu dan gerakan untuk setiap musim.'
      },
      {
        num:23, title:'Review (Jilid 2)',
        tujuan:'Review seluruh materi Jilid 2: animals, food, drinks, fruits, vegetables, likes/dislikes, clothes, weather, seasons.',
        kosakata:'Review semua kosakata dari pertemuan 13–22',
        ekspresi:'Review semua ekspresi dan dialog dari pertemuan sebelumnya.',
        grammar:'Review penggunaan "I like/don\'t like", "Do you like?", "It is…", "I am wearing…", "How\'s the weather?"',
        aktivitas:'Permainan kuis kelompok. Kelas dibagi menjadi 2 tim. Tebak gambar, tebak kata, dan dialog berantai.',
        latihan:'Soal review mencakup semua topik. Latihan reading, matching gambar, writing, dan speaking.',
        pr:'Belajar ulang semua materi Jilid 2 untuk persiapan Mid Test pertemuan berikutnya.',
        materi:'Pertemuan ini adalah review seluruh materi Jilid 2: animals (hewan), wild & farm animals (hewan liar & ternak), food (makanan), drinks (minuman), fruits (buah), vegetables (sayuran), likes & dislikes (suka & tidak suka), clothes (pakaian), weather (cuaca), dan seasons (musim). Pastikan siswa menguasai kosakata dan pola kalimat dasar sebelum Mid Test.',
        contoh_kalimat:'I like bananas. — Saya suka pisang.\nIt is a tiger. — Ini harimau.\nI am wearing a shirt. — Saya memakai kemeja.\nThe weather is sunny. — Cuacanya cerah.',
        contoh_percakapan:'A: Do you like cats?\nB: Yes, I like cats.\nA: What are you wearing?\nB: I am wearing a blue T-shirt.\nA: How\'s the weather today?\nB: It is rainy.',
        latihan_soal:'1. Apa bahasa Inggrisnya kucing? ____\n2. "Saya suka apel": ____\n3. Cuaca hujan: It is ____\n4. Sebutkan 3 hewan liar!\n5. Sebutkan 3 jenis pakaian!',
        tips:'Kuis interaktif dengan sistem poin. Tim pemenang mendapat hadiah kecil untuk motivasi.'
      },
      {
        num:24, title:'Mid Test',
        tujuan:'Mengukur pemahaman siswa terhadap seluruh materi Jilid 1 dan Jilid 2.',
        kosakata:'Semua kosakata dari Jilid 1 (pertemuan 1–12) dan Jilid 2 (pertemuan 13–22)',
        ekspresi:'Semua ekspresi dan dialog yang telah dipelajari.',
        grammar:'Semua pola kalimat yang telah dipelajari: This is…, I am…, I like…, Do you like…?, How\'s…?, What…?',
        aktivitas:'Evaluasi tertulis dan lisan. Siswa mengerjakan soal tertulis, kemudian tes speaking satu per satu.',
        latihan:'Soal reading comprehension, mencocokkan, menulis kalimat, dan speaking test.',
        pr:'Tidak ada PR. Istirahat dan persiapkan diri untuk Jilid 3!',
        materi:'Mid Test mencakup seluruh materi dari Jilid 1 (Pertemuan 1–12) dan Jilid 2 (Pertemuan 13–22). Bentuk tes: tertulis (reading, writing, vocabulary) dan lisan (speaking). Siswa akan diuji kemampuan menyapa, memperkenalkan diri, menyebutkan benda, warna, bentuk, anggota tubuh, hewan, makanan, pakaian, cuaca, serta menyatakan suka/tidak suka.',
        contoh_kalimat:'(Review semua materi)',
        contoh_percakapan:'(Test speaking: siswa berdialog dengan guru)',
        latihan_soal:'1. Sebutkan 7 hari dalam bahasa Inggris!\n2. Perkenalkan dirimu dalam 3 kalimat!\n3. Apa yang kamu pakai hari ini? (Jawab Inggris)\n4. Sebutkan 5 hewan dan 5 buah!\n5. Tanya cuaca hari ini dalam Inggris!',
        tips:'Buat suasana santai tapi serius. Beri pujian untuk setiap usaha siswa. Nilai bukan tujuan utama, tapi pemahaman.'
      }
    ]
  },
  {
    jilid:3, title:'Rumah & Kehidupan Sehari-hari', class:'c3',
    range:'Pertemuan 25–36', desc:'Mempelajari kosakata rumah, rutinitas harian, waktu, transportasi, dan profesi.',
    topics:['My House','Rooms','Furniture','Prepositions','Daily Activities','Time','Morning–Night','Simple Routine','Transportation','Places','Jobs','Review'],
    core:['My House','Daily Activities','Time','Transportation'],
    pertemuan:[
      {
        num:25, title:'My House',
        tujuan:'Siswa mampu menyebutkan bagian-bagian rumah dalam bahasa Inggris.',
        kosakata:'House (rumah), Home (rumah/kediaman), Door (pintu), Window (jendela), Wall (dinding), Floor (lantai), Roof (atap), Garden (taman), Garage (garasi), Fence (pagar), Stairs (tangga), Yard (halaman)',
        ekspresi:'This is my house. / My house is big. / I have a garden.',
        grammar:'Pola "This is my + noun" untuk menunjukkan kepemilikan. "My house is + adjective" untuk deskripsi.',
        aktivitas:'Picture discussion: guru menunjukkan gambar rumah, siswa menyebutkan bagian-bagian rumah dalam bahasa Inggris.',
        latihan:'Reading deskripsi rumah, speaking tentang rumah siswa, writing deskripsi rumah sederhana, mencocokkan gambar.',
        pr:'Gambar rumahmu dan beri label minimal 6 bagian rumah dalam bahasa Inggris.',
        materi:'Rumah (<em>house</em>) adalah tempat tinggal kita. Bagian-bagian rumah: house (rumah), door (pintu), window (jendela), wall (dinding), floor (lantai), roof (atap), garden (taman), garage (garasi), yard (halaman), fence (pagar). Untuk memperkenalkan rumah: "This is my house" (Ini rumahku). Untuk mendeskripsikan: "My house is big" (Rumahku besar). Perhatikan "house" mengacu pada bangunan, "home" mengacu pada tempat tinggal yang terasa nyaman.',
        contoh_kalimat:'This is my house. — Ini rumahku.\nMy house has a garden. — Rumahku punya taman.\nThe door is brown. — Pintunya coklat.\nI love my home. — Aku sayang rumahku.',
        contoh_percakapan:'A: Is this your house?\nB: Yes, this is my house.\nA: It is big! Do you have a garden?\nB: Yes, I have a garden.',
        latihan_soal:'1. Rumah dalam Inggris: ____\n2. "My house is big" artinya ____\n3. Sebutkan 4 bagian rumah dalam Inggris!\n4. Bagian rumah untuk menyimpan mobil: ____\n5. Lengkapi: "This is ____ house." (rumahku)',
        tips:'Minta siswa menggambar rumah impian mereka. Tunjukkan gambar rumah dari berbagai negara.'
      },
      {
        num:26, title:'Rooms',
        tujuan:'Siswa mampu menyebutkan nama-nama ruangan dalam rumah.',
        kosakata:'Bedroom (kamar tidur), Kitchen (dapur), Bathroom (kamar mandi), Living Room (ruang tamu), Dining Room (ruang makan), Study Room (ruang belajar), Laundry Room (ruang cuci), Basement (ruang bawah tanah), Attic (loteng)',
        ekspresi:'This is the bedroom. / I sleep in the bedroom. / Where is the kitchen?',
        grammar:'Gunakan "This is the + room" untuk menunjukkan ruangan. Gunakan "in" untuk menunjukkan lokasi: in the kitchen.',
        aktivitas:'Guru menunjukkan gambar denah rumah, siswa menunjuk dan menyebutkan nama ruangan dalam bahasa Inggris.',
        latihan:'Labeling gambar ruangan, membaca deskripsi ruangan, menulis fungsi setiap ruangan.',
        pr:'Gambar denah rumah sederhana, beri label 5 ruangan dalam bahasa Inggris.',
        materi:'Ruangan (<em>rooms</em>) di dalam rumah: bedroom (kamar tidur — tempat tidur/pakaian), kitchen (dapur — memasak/makanan), bathroom (kamar mandi — mandi/ke toilet), living room (ruang tamu — bersantai/tamu), dining room (ruang makan — makan), study room (ruang belajar — belajar/buku). Untuk menunjuk ruangan: "This is the kitchen" (Ini dapur). Untuk menyatakan kegiatan di ruangan: "I eat in the dining room."',
        contoh_kalimat:'This is the bedroom. — Ini kamar tidur.\nI sleep in the bedroom. — Saya tidur di kamar tidur.\nThe kitchen is for cooking. — Dapur untuk memasak.\nWe watch TV in the living room. — Kami nonton TV di ruang tamu.',
        contoh_percakapan:'A: What room is this?\nB: This is the kitchen.\nA: What do you do in the kitchen?\nB: I cook in the kitchen.',
        latihan_soal:'1. Kamar tidur dalam Inggris: ____\n2. "Bathroom" artinya ____\n3. Di ruangan apa kita makan? ____\n4. Sebutkan 4 ruangan dalam bahasa Inggris!\n5. Lengkapi: "I sleep in the ____."',
        tips:'Buat kartu ruangan. Bermain "Guess the Room" — guru mendeskripsikan kegiatan, siswa tebak ruangannya.'
      },
      {
        num:27, title:'Furniture',
        tujuan:'Siswa mampu menyebutkan nama-nama perabot rumah tangga.',
        kosakata:'Table (meja), Chair (kursi), Bed (tempat tidur), Cupboard (lemari), Shelf (rak), Wardrobe (lemari pakaian), Desk (meja tulis), Mirror (cermin), Sofa (sofa), Lamp (lampu), Clock (jam), Television (televisi)',
        ekspresi:'There is a table. / The bed is in the bedroom. / I have a new desk.',
        grammar:'Gunakan "There is + a/an + noun" untuk menyatakan keberadaan satu benda. "There are + noun + -s" untuk banyak benda.',
        aktivitas:'Matching game: guru menunjukkan gambar perabot, siswa menyebutkan nama dan ruangan tempatnya berada.',
        latihan:'Reading deskripsi ruangan dan perabot, writing kalimat tentang perabot, mencocokkan gambar.',
        pr:'Pilih satu ruangan di rumahmu. Tulis 5 kalimat tentang perabot yang ada di ruangan itu dalam bahasa Inggris.',
        materi:'Perabot rumah tangga (<em>furniture</em>): table (meja), chair (kursi), bed (tempat tidur), cupboard (lemari), shelf (rak), wardrobe (lemari pakaian), desk (meja tulis), mirror (cermin), sofa (sofa), lamp (lampu), clock (jam), television/ TV (televisi). Gunakan "There is…" untuk satu benda dan "There are…" untuk banyak benda: "There is a table in the kitchen" (Ada meja di dapur), "There are two chairs in the living room" (Ada dua kursi di ruang tamu).',
        contoh_kalimat:'There is a bed in the bedroom. — Ada tempat tidur di kamar tidur.\nThe lamp is on the table. — Lampu di atas meja.\nI have a new desk. — Saya punya meja baru.\nThe sofa is in the living room. — Sofa di ruang tamu.',
        contoh_percakapan:'A: What furniture is in your bedroom?\nB: There is a bed, a desk, and a wardrobe.\nA: Is there a mirror?\nB: Yes, there is a mirror.',
        latihan_soal:'1. Tempat tidur dalam Inggris: ____\n2. "Shelf" artinya ____\n3. "There ____ a chair" (is/are)\n4. Sebutkan 4 perabot dalam bahasa Inggris!\n5. Perabot apa yang ada di ruang tamu?',
        tips:'Gunakan katalog IKEA atau gambar dari majalah. Minta siswa membuat "furniture catalog" sederhana.'
      },
      {
        num:28, title:'Prepositions',
        tujuan:'Siswa mampu menggunakan kata depan tempat dalam kalimat sederhana.',
        kosakata:'In (di dalam), On (di atas), Under (di bawah), Behind (di belakang), Next to (di samping), In front of (di depan), Between (di antara), Above (di atas - tidak menyentuh)',
        ekspresi:'The cat is under the table. / The book is on the desk. / I sit next to Sari.',
        grammar:'Kata depan (preposition) menunjukkan posisi benda. Letaknya sebelum kata benda: in + the box, on + the table, under + the chair.',
        aktivitas:'"Object Hunt": guru menyembunyikan benda di kelas, siswa mencari dan mendeskripsikan posisinya: "The pencil is under the book."',
        latihan:'Reading kalimat dengan prepositions, writing letak benda, speaking mendeskripsikan posisi.',
        pr:'Letakkan 5 benda di posisi berbeda di rumah. Tulis 5 kalimat tentang posisi benda tersebut dalam bahasa Inggris.',
        materi:'Kata depan tempat (<em>prepositions of place</em>) menunjukkan posisi suatu benda: in (di dalam) — the pencil is in the box, on (di atas)— the book is on the table, under (di bawah) — the cat is under the chair, behind (di belakang) — the bag is behind the door, next to (di samping) — I sit next to Rina, in front of (di depan) — the teacher is in front of the class, between (di antara) — the ball is between the chairs.',
        contoh_kalimat:'The pencil is in the box. — Pensil di dalam kotak.\nThe book is on the table. — Buku di atas meja.\nThe cat is under the chair. — Kucing di bawah kursi.\nI sit next to my friend. — Saya duduk di samping teman.',
        contoh_percakapan:'A: Where is my pencil?\nB: It is under the book.\nA: Where is the cat?\nB: The cat is behind the door.',
        latihan_soal:'1. "In" artinya ____.\n2. "The book is ____ the table" (di atas)\n3. Dimana kucing? The cat is ____ the chair (di bawah)\n4. Sebutkan 3 kata depan dalam bahasa Inggris!\n5. Lengkapi: "I sit ____ ____ ____ Rina." (di samping)',
        tips:'Gunakan benda nyata untuk mendemonstrasikan preposisi. Letakkan benda di berbagai posisi dan tanyakan. Gerakan fisik sangat membantu.'
      },
      {
        num:29, title:'Daily Activities',
        tujuan:'Siswa mampu menyebutkan kegiatan sehari-hari dalam bahasa Inggris.',
        kosakata:'Wake up (bangun tidur), Brush teeth (gosok gigi), Take a bath (mandi), Get dressed (berpakaian), Eat breakfast (sarapan), Go to school (pergi ke sekolah), Study (belajar), Play (bermain), Eat lunch (makan siang), Take a nap (tidur siang), Watch TV (nonton TV), Go to bed (tidur)',
        ekspresi:'I wake up at six. / I brush my teeth. / I go to school.',
        grammar:'Gunakan Simple Present Tense untuk kegiatan rutin. Subjek I + verb 1: I wake up, I eat, I go. Tambahkan -s untuk he/she/it.',
        aktivitas:'Routine cards: siswa mengambil kartu bergambar aktivitas, lalu menyebutkannya dalam bahasa Inggris. Susun urutan kegiatan sehari-hari.',
        latihan:'Reading jadwal harian, writing rutinitas sendiri, speaking bercerita tentang kegiatan sehari-hari.',
        pr:'Tulis rutinitas harianmu dari bangun tidur sampai tidur lagi minimal 6 kalimat dalam bahasa Inggris.',
        materi:'Kegiatan sehari-hari (<em>daily activities/daily routine</em>) adalah hal yang kita lakukan setiap hari. Rutinitas pagi: wake up (bangun), brush teeth (gosok gigi), take a bath (mandi), get dressed (berpakaian), eat breakfast (sarapan), go to school (pergi ke sekolah). Rutinitas siang/sore: study (belajar), eat lunch (makan siang), play (bermain), take a nap (tidur siang). Rutinitas malam: watch TV (nonton TV), eat dinner (makan malam), do homework (kerjakan PR), go to bed (tidur).',
        contoh_kalimat:'I wake up at five o\'clock. — Saya bangun jam 5.\nI brush my teeth. — Saya gosok gigi.\nI go to school at seven. — Saya pergi ke sekolah jam 7.\nI play with my friends. — Saya bermain dengan teman.',
        contoh_percakapan:'A: What time do you wake up?\nB: I wake up at 5 o\'clock.\nA: What do you do after waking up?\nB: I brush my teeth and take a bath.',
        latihan_soal:'1. Bangun tidur dalam Inggris: ____\n2. "I go to school" artinya ____\n3. Setelah bangun, saya ____ (gosok gigi)\n4. Sebutkan 4 kegiatan pagi hari dalam Inggris!\n5. Lengkapi: "I ____ at 9 o\'clock." (tidur)',
        tips:'Buat "Daily Routine Chart" dengan gambar. Nyanyikan lagu "This is the Way" dari Super Simple Songs.'
      },
      {
        num:30, title:'Time',
        tujuan:'Siswa mampu membaca jam dalam bahasa Inggris.',
        kosakata:'O\'clock (tepat), Half past (lebih setengah), Quarter past (lebih seperempat), Quarter to (kurang seperempat), Hour (jam), Minute (menit), Clock (jam dinding), Watch (jam tangan), Time (waktu)',
        ekspresi:'What time is it? — It is three o\'clock. / It is half past seven.',
        grammar:'Pola: "It is + number + o\'clock" untuk jam tepat. "It is half past + number" untuk setengah. "It is quarter past/to + number" untuk seperempat.',
        aktivitas:'Bermain jam: guru memutar jarum jam, siswa menyebutkan waktunya. Siswa bergiliran memutar jam dan bertanya ke teman.',
        latihan:'Reading jam analog, writing waktu dalam kalimat, speaking menanyakan dan menyebutkan waktu.',
        pr:'Gambar 3 jam yang menunjukkan waktu berbeda. Tulis waktu tersebut dalam bahasa Inggris.',
        materi:'Membaca jam (<em>telling time</em>) dalam bahasa Inggris: untuk jam tepat gunakan "o\'clock": 3:00 = three o\'clock. Untuk setengah jam gunakan "half past": 7:30 = half past seven. Untuk seperempat: 7:15 = quarter past seven, 7:45 = quarter to eight. Untuk selain itu, sebut menitnya: 7:20 = seven twenty. Pertanyaan: "What time is it?" atau "What is the time?" (Jam berapa sekarang?).',
        contoh_kalimat:'What time is it? — Jam berapa?\nIt is five o\'clock. — Jam 5 tepat.\nIt is half past six. — Jam setengah 7.\nIt is quarter past seven. — Jam 7 lewat 15 menit.',
        contoh_percakapan:'A: What time is it?\nB: It is eight o\'clock.\nA: Thank you. I must go to school now.',
        latihan_soal:'1. Jam 3 tepat: It is three ____.\n2. "Half past seven" artinya ____\n3. 7:15 dalam Inggris: ____\n4. Tanya jam: "What ____ is it?"\n5. Gambar jam 9:00, tulis dalam Inggris!',
        tips:'Gunakan jam mainan atau jam dinding dengan jarum yang bisa digerakkan. Praktik setiap hari dengan menanyakan jam.'
      },
      {
        num:31, title:'Morning – Night',
        tujuan:'Siswa mampu menyebutkan pembagian waktu: pagi, siang, sore, malam.',
        kosakata:'Morning (pagi — 00–12), Afternoon (siang — 12–18), Evening (sore/malam — 18–24), Night (malam — gelap), Dawn (fajar), Noon (tengah hari), Midnight (tengah malam), Sunrise (matahari terbit), Sunset (matahari terbenam)',
        ekspresi:'Good morning! / Good afternoon! / Good evening! / Good night! / It is morning.',
        grammar:'Sapaan berbeda untuk waktu berbeda. "Good night" hanya untuk perpisahan/akan tidur, bukan sapaan saat bertemu.',
        aktivitas:'Urutkan gambar kegiatan dari pagi hingga malam. Siswa menyebutkan kegiatan dan waktunya dalam bahasa Inggris.',
        latihan:'Reading teks tentang waktu, writing kegiatan sesuai waktu, speaking menyapa sesuai waktu.',
        pr:'Tulis 4 kalimat: apa yang kamu lakukan di pagi, siang, sore, dan malam hari dalam bahasa Inggris.',
        materi:'Pembagian waktu dalam bahasa Inggris: morning (pagi — dari tengah malam hingga tengah hari), afternoon (siang — dari tengah hari hingga sore), evening (sore/malam — dari senja hingga tidur), night (malam — saat gelap). Sapaan: "Good morning" (pagi), "Good afternoon" (siang), "Good evening" (sore/malam — saat bertemu), "Good night" (selamat tidur — saat berpisah/akan tidur).',
        contoh_kalimat:'Good morning, Mom! — Selamat pagi, Bu!\nGood afternoon, friends! — Selamat siang, teman-teman!\nGood evening, Dad! — Selamat sore, Ayah!\nGood night! Sleep well. — Selamat tidur! Tidur yang nyenyak.',
        contoh_percakapan:'A: Good morning, Rina!\nB: Good morning, Sari!\nA: See you this afternoon!\nB: Yes, good afternoon!',
        latihan_soal:'1. Pagi dalam Inggris: ____\n2. Ucapkan "Selamat sore" dalam Inggris: ____\n3. "Good night" diucapkan ketika ____\n4. Pasangkan: 07:00 → Good ____, 14:00 → Good ____\n5. Lengkapi: "Good ____, friends!" (siang)',
        tips:'Setiap kali bertemu siswa, biasakan menyapa sesuai waktu. Tempel poster sapaan berdasarkan waktu di dinding kelas.'
      },
      {
        num:32, title:'Simple Routine',
        tujuan:'Siswa mampu bercerita tentang rutinitas harian menggunakan urutan waktu.',
        kosakata:'First (pertama), Then (kemudian), After that (setelah itu), Next (selanjutnya), Finally (akhirnya), Always (selalu), Usually (biasanya), Sometimes (kadang-kadang), Never (tidak pernah)',
        ekspresi:'First, I wake up. Then, I brush my teeth. After that, I take a bath. Finally, I go to school.',
        grammar:'Gunakan kata penghubung urutan: First, Then, After that, Next, Finally. Gunakan Simple Present Tense.',
        aktivitas:'Role play: siswa maju ke depan kelas dan mempraktikkan rutinitas harian sambil bercerita dalam bahasa Inggris. Bisa menggunakan gerakan.',
        latihan:'Reading cerita rutinitas harian, writing cerita sendiri, speaking presentasi di depan kelas.',
        pr:'Tulis cerita pendek (5–7 kalimat) tentang rutinitas harianmu dalam bahasa Inggris. Gunakan first, then, after that, finally.',
        materi:'Bercerita tentang rutinitas harian (<em>daily routine</em>) menggunakan kata urutan: First (pertama), Then (kemudian), After that (setelah itu), Next (selanjutnya), Finally (akhirnya). Contoh: "First, I wake up at 5 o\'clock. Then, I brush my teeth. After that, I take a bath. Next, I eat breakfast. Finally, I go to school." Gunakan adverb of frequency: always (selalu), usually (biasanya), sometimes (kadang-kadang), never (tidak pernah).',
        contoh_kalimat:'First, I wake up. — Pertama, saya bangun.\nThen, I eat breakfast. — Kemudian, saya sarapan.\nAfter that, I go to school. — Setelah itu, saya ke sekolah.\nFinally, I go to bed. — Akhirnya, saya tidur.',
        contoh_percakapan:'A: What do you do in the morning?\nB: First, I wake up. Then, I take a bath. After that, I eat breakfast. Finally, I go to school.',
        latihan_soal:'1. "First" artinya ____\n2. "Then" artinya ____\n3. Urutkan: ____ → Then → ____ → Finally\n4. Ceritakan rutinitas pagimu (3 kalimat)!\n5. "Finally, I go to bed" artinya ____',
        tips:'Minta siswa mempraktikkan dengan gerakan. "First" (angkat 1 jari), "Then" (angkat 2 jari), dll.'
      },
      {
        num:33, title:'Transportation',
        tujuan:'Siswa mampu menyebutkan alat transportasi dalam bahasa Inggris.',
        kosakata:'Car (mobil), Bus (bus), Train (kereta), Bicycle (sepeda), Motorcycle (sepeda motor), Airplane (pesawat), Ship (kapal), Boat (perahu), Bicycle (sepeda), Rickshaw (becak), Taxi (taksi)',
        ekspresi:'I go to school by bus. / The car is fast. / I ride a bicycle.',
        grammar:'Gunakan "by + vehicle" untuk alat transportasi: by car, by bus, by train. Gunakan "ride" untuk sepeda/motor, "drive" untuk mobil.',
        aktivitas:'Bingo transportasi: guru menyebutkan alat transportasi, siswa menandai gambar yang sesuai di kartu bingo.',
        latihan:'Reading teks tentang transportasi, matching gambar, writing cara pergi ke sekolah.',
        pr:'Tulis 5 alat transportasi dalam bahasa Inggris dan 1 kalimat tentang cara kamu pergi ke sekolah.',
        materi:'Alat transportasi (<em>transportation/vehicles</em>) dibagi menjadi: transportasi darat: car (mobil), bus (bus), train (kereta), motorcycle (sepeda motor), bicycle (sepeda), taxi (taksi), rickshaw (becak). Transportasi udara: airplane (pesawat), helicopter (helikopter). Transportasi air: ship (kapal), boat (perahu), ferry (feri). Gunakan "by" sebelum kendaraan: "I go to school by bus." Untuk sepeda dan motor, bisa gunakan "ride": "I ride a bicycle."',
        contoh_kalimat:'I go to school by bus. — Saya pergi ke sekolah naik bus.\nMy father drives a car. — Ayahku mengendarai mobil.\nThe train is long. — Keretanya panjang.\nI ride a bicycle on Sunday. — Saya naik sepeda hari Minggu.',
        contoh_percakapan:'A: How do you go to school?\nB: I go to school by motorcycle.\nA: Do you like riding a bicycle?\nB: Yes, I do. I like riding a bicycle.',
        latihan_soal:'1. Mobil dalam Inggris: ____\n2. "I go by bus" artinya ____\n3. Alat transportasi yang bisa terbang: ____\n4. Sebutkan 4 transportasi darat!\n5. Bagaimana caramu pergi ke sekolah? Jawab Inggris!',
        tips:'Buat kartu bingo transportasi. Tunjukkan video berbagai alat transportasi dari seluruh dunia.'
      },
      {
        num:34, title:'Places in Town',
        tujuan:'Siswa mampu menyebutkan nama-nama tempat umum di kota.',
        kosakata:'School (sekolah), Hospital (rumah sakit), Market (pasar), Park (taman), Library (perpustakaan), Supermarket (supermarket), Bank (bank), Post Office (kantor pos), Police Station (kantor polisi), Fire Station (stasiun pemadam), Mosque (masjid), Church (gereja)',
        ekspresi:'Where is the school? — The school is on Jalan Merdeka. / I go to the market.',
        grammar:'Gunakan "Where is…?" untuk menanyakan lokasi. Jawab: "It is on/in + location." Gunakan "go to the + place" untuk pergi ke suatu tempat.',
        aktivitas:'Map game: guru menunjukkan peta sederhana, siswa menunjuk dan menyebutkan tempat-tempat umum serta lokasinya.',
        latihan:'Reading petunjuk arah sederhana, writing lokasi tempat, speaking menanyakan dan memberi petunjuk arah.',
        pr:'Gambar peta sederhana dari rumah ke sekolah. Beri label 4 tempat yang kamu lewati dalam bahasa Inggris.',
        materi:'Tempat-tempat di kota (<em>places in town</em>): school (sekolah), hospital (rumah sakit), market (pasar), park (taman), library (perpustakaan), supermarket (supermarket), bank (bank), post office (kantor pos), police station (kantor polisi), fire station (stasiun pemadam kebakaran), mosque (masjid), church (gereja), temple (pura/vihara). Untuk menanyakan lokasi: "Where is the hospital?" (Dimana rumah sakit?). Untuk menjawab: "It is on Jalan Sudirman" atau "It is next to the bank."',
        contoh_kalimat:'Where is the library? — Dimana perpustakaan?\nThe school is on Jalan Merdeka. — Sekolah di Jalan Merdeka.\nI go to the park on Sunday. — Saya pergi ke taman hari Minggu.\nThe hospital is next to the bank. — Rumah sakit di samping bank.',
        contoh_percakapan:'A: Where is the market?\nB: The market is on Jalan Sudirman.\nA: Is it next to the bank?\nB: Yes, it is next to the bank.',
        latihan_soal:'1. Sekolah dalam Inggris: ____\n2. "Hospital" artinya ____\n3. Tanya lokasi: "____ is the market?"\n4. Sebutkan 4 tempat umum dalam Inggris!\n5. Tempat meminjam buku: ____',
        tips:'Gunakan Google Maps untuk menunjukkan tempat-tempat nyata di kota siswa. Buat peta kelas besar di papan tulis.'
      },
      {
        num:35, title:'Jobs',
        tujuan:'Siswa mampu menyebutkan nama-nama profesi dalam bahasa Inggris.',
        kosakata:'Teacher (guru), Doctor (dokter), Police (polisi), Farmer (petani), Chef/Cook (koki), Nurse (perawat), Driver (sopir), Pilot (pilot), Firefighter (pemadam kebakaran), Soldier (tentara), Artist (seniman), Singer (penyanyi)',
        ekspresi:'He is a doctor. / She is a teacher. / I want to be a pilot.',
        grammar:'Gunakan "He/She is a + profession" untuk menyatakan profesi seseorang. "I want to be a + profession" untuk cita-cita.',
        aktivitas:'Tebak profesi: guru mendeskripsikan pekerjaan, siswa menebak profesi dalam bahasa Inggris. Contoh: "This person helps sick people. Who is he?"',
        latihan:'Reading deskripsi pekerjaan, matching gambar profesi, writing cita-cita.',
        pr:'Tanyai 3 anggota keluargamu tentang profesi mereka. Tulis dalam bahasa Inggris: "My father is a…"',
        materi:'Profesi (<em>jobs/occupations</em>) dalam bahasa Inggris: teacher (guru), doctor (dokter), police (polisi), farmer (petani), chef/cook (koki), nurse (perawat), driver (sopir), pilot (pilot), firefighter (pemadam kebakaran), soldier (tentara), artist (seniman), singer (penyanyi), fisherman (nelayan), carpenter (tukang kayu). Gunakan "He is a…" untuk laki-laki dan "She is a…" untuk perempuan. Untuk menanyakan cita-cita: "What do you want to be?" (Kamu ingin jadi apa?).',
        contoh_kalimat:'He is a doctor. — Beliau seorang dokter.\nShe is a teacher. — Beliau seorang guru.\nI want to be a pilot. — Saya ingin menjadi pilot.\nMy father is a farmer. — Ayahku seorang petani.',
        contoh_percakapan:'A: What does your father do?\nB: My father is a teacher.\nA: What do you want to be?\nB: I want to be a doctor.',
        latihan_soal:'1. Guru dalam Inggris: ____\n2. "Doctor" artinya ____\n3. Ayahku seorang polisi: "My father ____ ____ police."\n4. Sebutkan 4 profesi dalam bahasa Inggris!\n5. Apa cita-citamu? Jawab dalam Inggris!',
        tips:'Undang orang tua dengan profesi berbeda untuk presentasi singkat. Bermain "dress-up" profesi.'
      },
      {
        num:36, title:'Review (Jilid 3)',
        tujuan:'Review seluruh materi Jilid 3: house, rooms, furniture, prepositions, daily activities, time, morning-night, routine, transportation, places, jobs.',
        kosakata:'Review semua kosakata dari pertemuan 25–35.',
        ekspresi:'Review semua ekspresi: This is…, There is/are…, Where is…?, What time…?, How do you go…?, What does he do?',
        grammar:'Review: There is/are, prepositions of place, Simple Present Tense, telling time, by + vehicle, He/She is a…',
        aktivitas:'Kuis kelompok dan permainan speaking. Tebak gambar dan dialog spontan.',
        latihan:'Soal review semua topik. Tes reading, writing, dan speaking.',
        pr:'Belajar ulang semua materi Jilid 3 untuk persiapan Jilid 4.',
        materi:'Review Jilid 3 mencakup: My House (rumahku), Rooms (ruangan), Furniture (perabot), Prepositions (kata depan), Daily Activities (kegiatan sehari-hari), Time (jam), Morning–Night (pagi–malam), Simple Routine (rutinitas), Transportation (transportasi), Places in Town (tempat umum), Jobs (profesi). Pastikan siswa mampu mendeskripsikan rumah, rutinitas, dan tempat-tempat di kota.',
        contoh_kalimat:'There is a table in the kitchen. — Ada meja di dapur.\nI wake up at 5 o\'clock. — Saya bangun jam 5.\nI go to school by bus. — Saya ke sekolah naik bus.\nHe is a doctor. — Beliau dokter.',
        contoh_percakapan:'A: Where is the book?\nB: It is on the table.\nA: What time do you wake up?\nB: I wake up at 5 o\'clock.',
        latihan_soal:'1. "There ____ a chair" (is/are)\n2. Jam 7:30 = half ____ seven\n3. Saya pergi ke sekolah naik bus: I go to school ____ bus\n4. Sebutkan 3 profesi!\n5. Dimana perpustakaan? ____ is the library?',
        tips:'Buat "mind map" besar di papan tulis yang menghubungkan semua topik Jilid 3. Kuis dengan hadiah.'
      }
    ]
  },
  {
    jilid:4, title:'Tata Bahasa & Percakapan', class:'c4',
    range:'Pertemuan 37–48', desc:'Penguasaan tata bahasa dasar, kalimat sederhana, percakapan, dan ujian akhir.',
    topics:['Opposites','Adjectives','Feelings','Review','Simple Sentences','There is/are','I Have / We Have','Can / Can\'t','Reading','Conversation','Final Review','Final Test'],
    core:['Simple Sentences','There is/are','Can / Can\'t','Conversation'],
    pertemuan:[
      {
        num:37, title:'Opposites',
        tujuan:'Siswa mampu menyebutkan pasangan kata berlawanan (antonim) dalam bahasa Inggris.',
        kosakata:'Big–Small (besar–kecil), Tall–Short (tinggi–pendek), Hot–Cold (panas–dingin), Fast–Slow (cepat–lambat), Long–Short (panjang–pendek), Old–New (tua/lama–baru), Clean–Dirty (bersih–kotor), Happy–Sad (senang–sedih), Open–Close (buka–tutup), Day–Night (siang–malam), Wet–Dry (basah–kering), Heavy–Light (berat–ringan)',
        ekspresi:'The elephant is big. The mouse is small. / It is hot today. / My bag is heavy.',
        grammar:'Gunakan "is/are + adjective" untuk mendeskripsikan. Kata sifat (adjective) menerangkan kata benda.',
        aktivitas:'Mencocokkan pasangan kata berlawanan. Guru menunjukkan satu kata, siswa mencari pasangan berlawanannya. Permainan berpasangan.',
        latihan:'Reading kalimat dengan kata sifat, matching opposites, writing kalimat dengan kata sifat berlawanan.',
        pr:'Cari 10 pasangan kata berlawanan dalam bahasa Inggris di buku atau internet. Tulis dalam buku tugas.',
        materi:'Kata berlawanan (<em>opposites/antonyms</em>) adalah pasangan kata dengan makna berlawanan. Contoh: big (besar) — small (kecil), tall (tinggi) — short (pendek), hot (panas) — cold (dingin), fast (cepat) — slow (lambat), clean (bersih) — dirty (kotor), happy (senang) — sad (sedih), open (buka) — close (tutup), day (siang) — night (malam), wet (basah) — dry (kering), heavy (berat) — light (ringan), old (tua/lama) — new (baru), long (panjang) — short (pendek).',
        contoh_kalimat:'The elephant is big. — Gajah itu besar.\nThe mouse is small. — Tikus itu kecil.\nIt is hot today. — Hari ini panas.\nMy bag is heavy. — Tasku berat.',
        contoh_percakapan:'A: Is the elephant big or small?\nB: The elephant is big.\nA: Is the mouse big or small?\nB: The mouse is small.',
        latihan_soal:'1. Lawan dari "big" adalah ____\n2. Lawan dari "hot" adalah ____\n3. The opposite of "happy" is ____\n4. Sebutkan 3 pasangan kata berlawanan!\n5. Lengkapi: "The opposite of tall is ____"',
        tips:'Gunakan gerakan tubuh untuk menunjukkan kata sifat. Big (rentangkan tangan), small (satukan jari), dll.'
      },
      {
        num:38, title:'Adjectives',
        tujuan:'Siswa mampu menggunakan kata sifat untuk mendeskripsikan benda dan orang.',
        kosakata:'Beautiful (cantik/indah), Kind (baik hati), Brave (berani), Funny (lucu), Smart (pintar), Strong (kuat), Weak (lemah), Fast (cepat), Slow (lambat), Clean (bersih), Dirty (kotor), Soft (lembut), Hard (keras), Smooth (halus), Rough (kasar)',
        ekspresi:'She is kind. / The flower is beautiful. / He is a brave boy.',
        grammar:'Kata sifat (adjective) diletakkan sebelum kata benda: a beautiful flower, atau setelah kata kerja "is/am/are": The flower is beautiful.',
        aktivitas:'Deskripsikan gambar: guru menunjukkan gambar, siswa menyebutkan kata sifat yang sesuai dalam bahasa Inggris.',
        latihan:'Reading teks deskripsi, writing kalimat dengan adjectives, speaking mendeskripsikan benda/teman.',
        pr:'Ambil 5 benda di rumah. Tulis 5 kalimat mendeskripsikan benda tersebut dengan kata sifat dalam bahasa Inggris.',
        materi:'Kata sifat (<em>adjectives</em>) digunakan untuk menerangkan kata benda (noun). Adjectives memberi informasi tentang ukuran, warna, bentuk, perasaan, dan kualitas. Letak adjectives: (1) sebelum noun: a beautiful flower, a brave boy, a funny story; (2) setelah verb "to be" (is/am/are): She is kind, The flower is beautiful. Beberapa adjectives umum: beautiful (cantik), kind (baik), brave (berani), funny (lucu), smart (pintar), strong (kuat), weak (lemah), soft (lembut), hard (keras).',
        contoh_kalimat:'She is a kind teacher. — Beliau guru yang baik.\nThe flower is beautiful. — Bunga itu indah.\nHe is a brave boy. — Dia anak yang berani.\nMy cat is funny. — Kucingku lucu.',
        contoh_percakapan:'A: What is your mother like?\nB: My mother is kind and beautiful.\nA: Is your father brave?\nB: Yes, my father is brave.',
        latihan_soal:'1. "Beautiful" artinya ____\n2. Letakkan adjective: "a ____ flower" (cantik)\n3. "My teacher is ____" (baik)\n4. Sebutkan 3 kata sifat dalam bahasa Inggris!\n5. Deskripsikan ibumu dalam 2 kalimat!',
        tips:'Bawa benda dengan tekstur berbeda (halus/kasar/lembut) untuk dideskripsikan. Gambar orang dengan ekspresi berbeda.'
      },
      {
        num:39, title:'Feelings',
        tujuan:'Siswa mampu menyebutkan perasaan/emosi dalam bahasa Inggris.',
        kosakata:'Happy (senang), Sad (sedih), Angry (marah), Tired (lelah), Scared (takut), Hungry (lapar), Thirsty (haus), Sleepy (mengantuk), Surprised (terkejut), Bored (bosan), Excited (bersemangat), Calm (tenang)',
        ekspresi:'How do you feel? — I am happy. / I feel tired. / She is sad.',
        grammar:'Gunakan "I am + feeling" atau "I feel + feeling" untuk menyatakan perasaan. "How do you feel?" untuk menanyakan perasaan.',
        aktivitas:'Kartu emosi: guru menunjukkan kartu bergambar ekspresi, siswa menyebutkan perasaannya dalam bahasa Inggris dan menirukan ekspresinya.',
        latihan:'Reading cerita tentang perasaan, matching gambar ekspresi, writing jurnal perasaan hari ini.',
        pr:'Tulis perasaanmu hari ini dalam bahasa Inggris. Jelaskan mengapa kamu merasa seperti itu (1-2 kalimat).',
        materi:'Perasaan (<em>feelings/emotions</em>) dalam bahasa Inggris: happy (senang), sad (sedih), angry (marah), tired (lelah), scared (takut), hungry (lapar), thirsty (haus), sleepy (mengantuk), surprised (terkejut), bored (bosan), excited (bersemangat), calm (tenang). Untuk menanyakan perasaan: "How do you feel?" (Bagaimana perasaanmu?). Jawab: "I am happy" (Saya senang) atau "I feel tired" (Saya merasa lelah).',
        contoh_kalimat:'I am happy today. — Saya senang hari ini.\nShe is sad. — Dia sedih.\nHe is angry. — Dia marah.\nI feel tired. — Saya merasa lelah.',
        contoh_percakapan:'A: How do you feel today?\nB: I am happy!\nA: Why are you happy?\nB: Because I got a good grade.',
        latihan_soal:'1. "Happy" artinya ____\n2. "I am tired" artinya ____\n3. Tanya perasaan: "How ____ you feel?"\n4. Sebutkan 4 perasaan dalam bahasa Inggris!\n5. Apa yang membuatmu happy hari ini?',
        tips:'Buat "Feelings Chart" dengan foto ekspresi siswa sendiri. Setiap hari tanya dan catat perasaan mereka.'
      },
      {
        num:40, title:'Review',
        tujuan:'Review materi adjectives, opposites, feelings dari pertemuan 37–39.',
        kosakata:'Semua adjectives, opposites, dan feelings yang telah dipelajari.',
        ekspresi:'Review: How do you feel? / The opposite of… / She is kind and beautiful.',
        grammar:'Review posisi adjective dan penggunaan is/am/are.',
        aktivitas:'Kuis game: tebak gambar, tebak kata berlawanan, tebak perasaan. Speaking test sederhana.',
        latihan:'Soal review opposites, adjectives, feelings. Latihan reading, writing, dan speaking.',
        pr:'Belajar ulang untuk persiapan materi Simple Sentences.',
        materi:'Review pertemuan 37–39 mencakup: Opposites (kata berlawanan), Adjectives (kata sifat), Feelings (perasaan). Pastikan siswa mampu: (1) menyebutkan pasangan kata berlawanan, (2) menggunakan adjective untuk mendeskripsikan benda/orang, (3) menanyakan dan menjawab perasaan.',
        contoh_kalimat:'The opposite of big is small. — Lawan besar adalah kecil.\nShe is a beautiful girl. — Dia gadis yang cantik.\nI am happy today. — Saya senang hari ini.',
        contoh_percakapan:'A: How do you feel?\nB: I am happy.\nA: What is the opposite of happy?\nB: The opposite of happy is sad.',
        latihan_soal:'1. Lawan dari "big" adalah ____\n2. "Beautiful" artinya ____\n3. I am ____ (lapar)\n4. "She is kind" artinya ____\n5. Buat 1 kalimat dengan adjective!',
        tips:'Permainan "Opposite Race" — siswa berlomba mencari pasangan kata berlawanan.'
      },
      {
        num:41, title:'Simple Sentences',
        tujuan:'Siswa mampu membentuk kalimat sederhana dengan pola yang benar.',
        kosakata:'This is… (ini…), That is… (itu…), These are… (ini… - jamak), Those are… (itu… - jamak), Subject (subjek), Verb (kata kerja), Object (objek)',
        ekspresi:'This is my book. / That is a pencil. / These are my pencils.',
        grammar:'Pola: This is + noun (tunggal/dekat), That is + noun (tunggal/jauh), These are + noun + s (jamak/dekat), Those are + noun + s (jamak/jauh).',
        aktivitas:'Sentence building: guru memberikan kartu kata, siswa menyusunnya menjadi kalimat yang benar. Praktik menunjuk benda dan membuat kalimat.',
        latihan:'Reading kalimat sederhana, writing menyusun kalimat, speaking membuat kalimat tentang benda di kelas.',
        pr:'Tulis 10 kalimat sederhana menggunakan "This is", "That is", "These are", "Those are" tentang benda di rumahmu.',
        materi:'Kalimat sederhana (<em>simple sentences</em>) adalah dasar komunikasi dalam bahasa Inggris. Pola: Subject + Verb + Object. Untuk menunjukkan benda: This is (ini — untuk benda dekat tunggal): This is a book. That is (itu — untuk benda jauh tunggal): That is a bag. These are (ini — untuk benda dekat jamak): These are pencils. Those are (itu — untuk benda jauh jamak): Those are chairs. Perhatikan perbedaan "is" (tunggal) dan "are" (jamak).',
        contoh_kalimat:'This is my book. — Ini bukuku.\nThat is a pencil. — Itu pensil.\nThese are my books. — Ini buku-bukuku.\nThose are chairs. — Itu kursi-kursi.',
        contoh_percakapan:'A: What is this?\nB: This is a book.\nA: What are these?\nB: These are pencils.',
        latihan_soal:'1. Lengkapi: "This ____ a book." (is/are)\n2. "Those are chairs" — "Those" untuk benda ____ (dekat/jauh)\n3. Ubah ke jamak: "This is a book" → ____\n4. "These" untuk benda ____ (tunggal/jamak)\n5. Buat 1 kalimat: "____ is my pencil." (ini)',
        tips:'Gunakan benda di kelas sebagai alat peraga. Ajak siswa menunjuk dan membuat kalimat.'
      },
      {
        num:42, title:'There is / There are',
        tujuan:'Siswa mampu menyatakan keberadaan benda menggunakan "There is" dan "There are".',
        kosakata:'There is (ada — tunggal), There are (ada — jamak), Some (beberapa), Any (apapun), A lot of (banyak), A few (sedikit)',
        ekspresi:'There is a cat on the chair. / There are three books on the table. / Is there a pen?',
        grammar:'"There is" untuk benda tunggal/tidak bisa dihitung (uncountable). "There are" untuk benda jamak (plural). Tanya: "Is there…?" / "Are there…?"',
        aktivitas:'Deskripsi gambar: guru menunjukkan gambar ruangan, siswa menyebutkan benda-benda yang ada menggunakan "There is" dan "There are".',
        latihan:'Reading deskripsi gambar, writing kalimat tentang keberadaan benda, speaking tanya-jawab tentang gambar.',
        pr:'Gambar sebuah ruangan. Tulis 5 kalimat tentang benda yang ada di ruangan itu menggunakan "There is" dan "There are".',
        materi:'"There is" dan "There are" digunakan untuk menyatakan keberadaan sesuatu. "There is" diikuti kata benda tunggal (<em>singular noun</em>) atau benda yang tidak bisa dihitung (<em>uncountable noun</em>): "There is a cat" (Ada kucing), "There is some water" (Ada air). "There are" diikuti kata benda jamak (<em>plural noun</em>): "There are three cats" (Ada tiga kucing). Untuk bertanya: "Is there a…?" (Apakah ada…?) dan "Are there any…?" (Apakah ada beberapa…?).',
        contoh_kalimat:'There is a cat on the chair. — Ada kucing di kursi.\nThere are three books on the table. — Ada tiga buku di meja.\nThere is some milk in the glass. — Ada susu di gelas.\nAre there any pencils? — Apakah ada pensil?',
        contoh_percakapan:'A: What is in your bag?\nB: There is a book and a pencil.\nA: Is there a ruler?\nB: No, there is not.',
        latihan_soal:'1. Bilang: "Ada kucing": There ____ a cat.\n2. Bilang: "Ada tiga buku": There ____ three books.\n3. Tanya: "____ there a pen?"\n4. "There are" untuk benda ____\n5. Deskripsikan isi kelasmu (2 kalimat)!',
        tips:'Gunakan gambar-gambar dengan banyak detail. Minta siswa mencari dan menyebutkan benda-benda dalam gambar.'
      },
      {
        num:43, title:'I Have / We Have',
        tujuan:'Siswa mampu menyatakan kepemilikan menggunakan "have" dan "has".',
        kosakata:'Have (punya — I, you, we, they), Has (punya — he, she, it), I have (saya punya), You have (kamu punya), We have (kami punya), They have (mereka punya), He has (dia punya — laki), She has (dia punya — perempuan), It has (dia punya — benda/hewan)',
        ekspresi:'I have a pencil. / She has a book. / What do you have? / Do you have a ruler?',
        grammar:'Penggunaan "have" dan "has": I/You/We/They + have, He/She/It + has. Tanya: "Do you have…?" "Does he have…?"',
        aktivitas:'Pair work: siswa bertanya ke teman tentang benda yang mereka miliki. "What do you have?" "I have a pencil." Catat dan laporkan.',
        latihan:'Reading dialog, writing kalimat kepemilikan, speaking tanya-jawab tentang kepemilikan.',
        pr:'Buat daftar 5 benda yang kamu miliki dan 5 benda yang anggota keluargamu miliki. Tulis dalam bahasa Inggris.',
        materi:'Menyatakan kepemilikan (<em>possession</em>) menggunakan kata kerja "have" dan "has". Subjek I, You, We, They menggunakan "have": I have a pencil (Saya punya pensil), We have books (Kami punya buku). Subjek He, She, It menggunakan "has": She has a bag (Dia punya tas), He has a ruler (Dia punya penggaris). Untuk bertanya: "Do you have…?" (Apakah kamu punya?) dan "Does she have…?" (Apakah dia punya?).',
        contoh_kalimat:'I have a pencil. — Saya punya pensil.\nShe has a book. — Dia punya buku.\nWe have a big house. — Kami punya rumah besar.\nDo you have a pet? — Apakah kamu punya hewan peliharaan?',
        contoh_percakapan:'A: Do you have a pet?\nB: Yes, I have a cat.\nA: Does she have a pet?\nB: No, she does not have a pet.',
        latihan_soal:'1. "I ____ a pencil" (have/has)\n2. "She ____ a book" (have/has)\n3. Tanya: "____ you have a ruler?"\n4. "They have" artinya ____\n5. Apa yang kamu miliki? Jawab dalam Inggris!',
        tips:'Bawa tas berisi benda-benda. Minta siswa maju dan mengeluarkan benda satu per satu sambil bilang "I have a…"'
      },
      {
        num:44, title:'Can / Can\'t',
        tujuan:'Siswa mampu menyatakan kemampuan dan ketidakmampuan dalam bahasa Inggris.',
        kosakata:'Can (bisa/dapat), Can\'t/Cannot (tidak bisa), Run (lari), Swim (berenang), Fly (terbang), Sing (menyanyi), Dance (menari), Draw (menggambar), Read (membaca), Write (menulis), Climb (memanjat), Jump (meloncat)',
        ekspresi:'I can swim. / I can\'t fly. / Can you run fast? / Yes, I can. / No, I can\'t.',
        grammar:'"Can" diikuti kata kerja (verb) tanpa "to": can swim, can fly, can read. Tidak berubah untuk subjek apapun. Tanya: "Can + subject + verb?"',
        aktivitas:'Action game: guru menyebutkan aktivitas, jika siswa bisa melakukannya mereka berdiri sambil bilang "I can…" Jika tidak, tetap duduk bilang "I can\'t…"',
        latihan:'Reading tentang kemampuan, writing kalimat kemampuan, speaking tanya-jawab tentang kemampuan diri dan teman.',
        pr:'Tulis 5 kalimat tentang hal yang bisa kamu lakukan dan 3 kalimat tentang hal yang tidak bisa kamu lakukan dalam bahasa Inggris.',
        materi:'"Can" adalah kata kerja bantu (<em>modal verb</em>) yang menyatakan kemampuan. Pola: Subject + can + verb 1 (tanpa to): I can swim (Saya bisa berenang), She can sing (Dia bisa menyanyi). Bentuk negatif: can\'t / cannot (tidak bisa): I can\'t fly (Saya tidak bisa terbang). Untuk bertanya: Can + subject + verb? — "Can you run fast?" (Apakah kamu bisa lari cepat?). Jawaban: "Yes, I can" atau "No, I can\'t."',
        contoh_kalimat:'I can swim. — Saya bisa berenang.\nShe can sing. — Dia bisa menyanyi.\nI can\'t fly. — Saya tidak bisa terbang.\nCan you draw a cat? — Bisakah kamu menggambar kucing?',
        contoh_percakapan:'A: Can you swim?\nB: Yes, I can swim.\nA: Can you fly?\nB: No, I can\'t fly.',
        latihan_soal:'1. "I ____ swim" (bisa)\n2. "Can\'t" adalah singkatan dari ____\n3. Tanya: "____ you dance?"\n4. "I can\'t fly" artinya ____\n5. Sebutkan 2 hal yang bisa kamu lakukan!',
        tips:'Gerakan fisik sangat efektif. Setiap kata kerja, tunjukkan gerakannya: swim (gerakan berenang), fly (mengepak seperti burung).'
      },
      {
        num:45, title:'Reading Practice',
        tujuan:'Siswa mampu membaca dan memahami teks pendek bahasa Inggris.',
        kosakata:'Story (cerita), Read (baca), Understand (pahami), Aloud (nyaring), Character (tokoh), Title (judul), New words (kata baru), Meaning (arti)',
        ekspresi:'Let\'s read. / Read aloud, please. / What is the story about? / I understand.',
        grammar:'Review semua pola kalimat yang telah dipelajari dalam konteks cerita pendek.',
        aktivitas:'Siswa membaca cerita pendek bergambar secara bergiliran. Setelah membaca, jawab pertanyaan pemahaman.',
        latihan:'Reading comprehension: baca teks, jawab pertanyaan, cari arti kata baru, ceritakan kembali isi cerita.',
        pr:'Pinjam buku cerita bahasa Inggris di perpustakaan atau baca cerita online. Tulis 3 kata baru yang kamu pelajari.',
        materi:'Membaca (<em>reading</em>) adalah keterampilan penting dalam belajar bahasa. Bacalah teks dengan nyaring (<em>read aloud</em>) untuk melatih pelafalan. Perhatikan tanda baca: titik (.) berhenti, koma (,) jeda sebentar. Tips membaca: (1) lihat gambarnya untuk membantu pemahaman, (2) baca perlahan, (3) cari arti kata yang tidak dikenal, (4) baca lagi sampai paham. Contoh teks: "This is my cat. His name is Kitty. He is small and white. He can run fast. I love my cat."',
        contoh_kalimat:'Let\'s read the story. — Mari baca ceritanya.\nRead aloud, please. — Baca nyaring, tolong.\nWhat is the story about? — Tentang apa ceritanya?\nI understand the story. — Saya paham ceritanya.',
        contoh_percakapan:'A: What is the story about?\nB: It is about a cat.\nA: What is the cat\'s name?\nB: The cat\'s name is Kitty.',
        latihan_soal:'Baca teks: "This is a cat. It is black. It can climb a tree. It likes milk." \n1. What animal is it? ____\n2. What color is the cat? ____\n3. What can the cat do? ____\n4. Apa yang disukai kucing? ____\n5. Beri judul cerita ini!',
        tips:'Gunakan buku cerita bergambar (picture books) dengan kalimat sederhana. Beri stiker untuk setiap buku yang selesai dibaca.'
      },
      {
        num:46, title:'Conversation',
        tujuan:'Siswa mampu melakukan percakapan sederhana dalam bahasa Inggris.',
        kosakata:'Dialog (percakapan), Role play (bermain peran), Greeting (sapaan), Question (pertanyaan), Answer (jawaban), Polite (sopan), Please (tolong), Thank you (terima kasih), Sorry (maaf), Excuse me (permisi)',
        ekspresi:'Excuse me. / Thank you. / You\'re welcome. / I\'m sorry. / Can you help me? / Sure.',
        grammar:'Review semua pola kalimat yang telah dipelajari. Fokus pada intonasi dan pelafalan yang benar.',
        aktivitas:'Dialog berpasangan: siswa berpasangan dan mempraktikkan dialog tentang perkenalan, menanyakan kabar, meminta bantuan, dll.',
        latihan:'Reading dialog, writing dialog sederhana, speaking dialog di depan kelas.',
        pr:'Buat dialog pendek (4–6 baris) antara dua orang dan praktikkan dengan teman atau anggota keluarga.',
        materi:'Percakapan (<em>conversation/dialogue</em>) adalah komunikasi dua arah. Percakapan biasanya dimulai dengan sapaan (<em>greeting</em>), lalu topik utama, dan diakhiri dengan penutup (<em>farewell</em>). Gunakan kata-kata sopan: Please (tolong), Thank you (terima kasih), You\'re welcome (sama-sama), I\'m sorry (maaf), Excuse me (permisi). Contoh percakapan: "A: Excuse me, can you help me? B: Sure. A: What time is it? B: It is three o\'clock. A: Thank you. B: You\'re welcome."',
        contoh_kalimat:'Thank you very much. — Terima kasih banyak.\nYou\'re welcome. — Sama-sama.\nExcuse me, where is the toilet? — Permisi, dimana toilet?\nCan you help me, please? — Bisakah kau membantuku?',
        contoh_percakapan:'A: Excuse me, can you help me?\nB: Sure.\nA: Where is the library?\nB: It is on Jalan Merdeka.\nA: Thank you very much.\nB: You\'re welcome.',
        latihan_soal:'1. "Thank you" dijawab: "You\'re ____"\n2. Bilang "Maaf" dalam Inggris: ____\n3. Bilang "Tolong" dalam Inggris: ____\n4. Buat dialog perkenalan (4 baris)!\n5. Apa yang kamu katakan jika mau bertanya?',
        tips:'Buat sudut "English Corner" di kelas. Setiap pertemuan, luangkan 5 menit untuk free conversation.'
      },
      {
        num:47, title:'Final Review',
        tujuan:'Review seluruh materi dari Jilid 1 sampai Jilid 4 sebagai persiapan ujian akhir.',
        kosakata:'Semua kosakata dari pertemuan 1–46.',
        ekspresi:'Semua ekspresi dan dialog yang telah dipelajari selama program.',
        grammar:'Semua pola kalimat: Greetings, Introduction, This is/That is, I like/Don\'t like, There is/are, I have/She has, Can/Can\'t, Simple Present Tense, Prepositions.',
        aktivitas:'Games & speaking: kuis komprehensif, tebak kata, dialog spontan, dan presentasi singkat. Review semua keterampilan.',
        latihan:'Soal review komprehensif: reading, writing, listening (guru bacakan), dan speaking. Simulasi ujian.',
        pr:'Persiapkan diri untuk Final Test. Baca ulang catatan. Istirahat yang cukup.',
        materi:'Final Review mencakup seluruh materi program Bahasa Inggris SD Kelas 1–3 (48 pertemuan, 4 jilid). Review dimulai dari Jilid 1 (Greetings, Introduction, Alphabet, Numbers, Colors, Shapes, Classroom Objects, Commands, Days, Family, Body Parts, Five Senses), Jilid 2 (Animals, Food, Drinks, Fruits, Vegetables, Likes/Dislikes, Clothes, Weather, Seasons), Jilid 3 (House, Rooms, Furniture, Prepositions, Daily Activities, Time, Routine, Transportation, Places, Jobs), Jilid 4 (Opposites, Adjectives, Feelings, Simple Sentences, There is/are, Have/Has, Can/Can\'t, Reading, Conversation).',
        contoh_kalimat:'Good morning! My name is Budi. — Selamat pagi! Nama saya Budi.\nI like apples. — Saya suka apel.\nThere is a cat under the table. — Ada kucing di bawah meja.\nI can swim. — Saya bisa berenang.',
        contoh_percakapan:'A: Good morning! What is your name?\nB: Good morning! My name is Siti.\nA: How are you today?\nB: I am happy. I like English class.',
        latihan_soal:'1. Perkenalkan dirimu (3 kalimat)!\n2. Sebutkan 7 hari dan 12 bulan!\n3. Buat 2 kalimat menggunakan "There is" dan "There are"!\n4. Apa yang bisa kamu lakukan? Jawab dengan "I can"!\n5. Buat dialog pendek antara 2 orang!',
        tips:'Review yang menyenangkan dengan games. Buat "review race" — kelompok berlomba menjawab soal. Beri semangat.'
      },
      {
        num:48, title:'Final Test',
        tujuan:'Mengukur pemahaman siswa terhadap seluruh materi program 48 pertemuan.',
        kosakata:'Semua kosakata yang telah dipelajari dalam program (Jilid 1–4)',
        ekspresi:'Semua ekspresi dan dialog dari seluruh materi.',
        grammar:'Semua pola kalimat: Simple Present, There is/are, Have/Has, Can/Can\'t, Prepositions, Adjectives, Questions.',
        aktivitas:'Evaluasi akhir mencakup 4 keterampilan: Listening (guru bacakan), Speaking (wawancara singkat), Reading (baca & pahami), Writing (tulis kalimat).',
        latihan:'Soal lengkap: listening comprehension, vocabulary, grammar, reading comprehension, writing, dan speaking test.',
        pr:'Selamat! Siswa telah menyelesaikan program Bahasa Inggris SD Kelas 1–3 (48 pertemuan). Teruslah berlatih!',
        materi:'Final Test adalah ujian akhir program Bahasa Inggris SD Kelas 1–3. Materi mencakup seluruh 48 pertemuan dari Jilid 1 hingga Jilid 4. Bentuk tes: (1) Listening — guru membacakan kata/kalimat, siswa memilih/menulis, (2) Speaking — siswa menjawab pertanyaan dan melakukan dialog singkat, (3) Reading — siswa membaca teks pendek dan menjawab pertanyaan, (4) Writing — siswa menulis kalimat dan paragraf pendek. Selamat! Siswa telah menyelesaikan program 48 pertemuan dengan 4 jilid. Teruslah berlatih dan kembangkan kemampuan bahasa Inggris!',
        contoh_kalimat:'Good luck on your test! — Semoga berhasil!\nYou can do it! — Kamu bisa!\nCongratulations! — Selamat!',
        contoh_percakapan:'Teacher: Good morning. What is your name?\nStudent: Good morning. My name is Andi.\nTeacher: Nice to meet you. Can you tell me about your family?\nStudent: Yes. I have a father, a mother, and one sister.',
        latihan_soal:'BAGIAN A — Listening: Guru akan membacakan 5 kata, tulis dalam bahasa Inggris.\nBAGIAN B — Vocabulary: Sebutkan 10 benda di kelas dalam Inggris!\nBAGIAN C — Grammar: Buat 3 kalimat dengan "There is" atau "There are"!\nBAGIAN D — Reading: Baca teks dan jawab 3 pertanyaan!\nBAGIAN E — Speaking: Perkenalkan dirimu dan jawab pertanyaan guru!',
        tips:'Buat suasana ujian yang nyaman. Ingatkan siswa bahwa tes ini untuk mengukur perkembangan, bukan untuk menghukum. Beri hadiah kecil untuk semua peserta sebagai penghargaan telah menyelesaikan program!'
      }
    ]
  }
];
